/**
 * Game content data — DOGS, ZONES, ITEMS, THREATS, COMPANIONS
 *
 * v2.1 — Full port of the v1 world (19 zones, 15 companions, 69 items, 45 threats)
 * into v2's strict types. Merged from v2 dog data + turbo-game-v1-archive content.
 * Safe to edit by hand afterwards.
 */

import type { Dog, Zone, Item, Threat, Companion } from './types';

export const DOGS: Record<string, Dog> = {
  turbo: {
    id: 'turbo',
    name: 'Turbo',
    breed: 'Alaskan Husky',
    trait: 'speed' as const,
    traitDesc: 'Moves faster, escapes threats quicker',
    colors: { fur: ['#ffffff', '#3a3a3a', '#8B4513'], accent: '#4a9eff' },
    personality: ['adventurous', 'loyal', 'curious'] as const,
    lines: {
      intro: "The gate was open. I don't remember opening it... but the world is OUTSIDE.",
      happy: "Woof! Best day ever!",
      scared: "What was that?! ...I'm not scared. I'm just cautiously observant.",
      hint: "I smell something familiar... like home?",
      combat: "Leave it to me! *growls bravely*",
      foundFriend: "A new friend?! *wags tail furiously*"
    }
  },
  watson: {
    id: 'watson',
    name: 'Watson',
    breed: 'German Shepherd',
    trait: 'brave' as const,
    traitDesc: 'Combat is easier, intimidation works',
    colors: { fur: ['#2a1a0a', '#4a2a0a', '#1a0a00'], accent: '#d4a020' },
    personality: ['brave', 'protective', 'disciplined'] as const,
    lines: {
      intro: "I don't know where I am, but if anything threatens anyone, it'll answer to me.",
      happy: "*stays alert but tail gives a small wag*",
      scared: "*ears flatten, then stands taller* I'm fine. Really.",
      hint: "That direction... I should investigate.",
      combat: "Not on my watch. *steps forward*",
      foundFriend: "A fellow warrior? ...Do you know the way home?"
    }
  },
  nova: {
    id: 'nova',
    name: 'Nova',
    breed: 'Golden Retriever',
    trait: 'happiness' as const,
    traitDesc: 'Companions boost more, morale decays slower',
    colors: { fur: ['#DAA520', '#FFD700', '#B8860B'], accent: '#ff9f43' },
    personality: ['friendly', 'optimistic', 'generous'] as const,
    lines: {
      intro: "Oh wow! Everything is so big and new! I hope I make lots of friends!",
      happy: "This is the BEST thing that's ever happened! *does happy pirouette*",
      scared: "*whimpers* ...But I'll be brave for everyone!",
      hint: "Ooh! A clue! Maybe we're getting closer to home!",
      combat: "*barks confidently* They won't hurt my friends!",
      foundFriend: "A new friend?! *immediately starts playing*"
    }
  },
  walter: {
    id: 'walter',
    name: 'Walter',
    breed: 'English Bulldog',
    trait: 'sniff' as const,
    traitDesc: 'Finds food and hints faster',
    colors: { fur: ['#D2B48C', '#C4A882', '#8B7355'], accent: '#e07040' },
    personality: ['food-motivated', 'calm', 'stubborn'] as const,
    lines: {
      intro: "I was napping... now I'm somewhere else. Hope there's food here.",
      happy: "*pants happily* Nothing beats a good day and a good snack.",
      scared: "*huffs* I'm not afraid of... *hears noise* ...of anything.",
      hint: "*sniff sniff* ...Yeah, that smells like home. Definitely home.",
      combat: "*stands his ground, looking like he's about to sneeze*",
      foundFriend: "*sniffs new dog* ...Do you have snacks? ...Wait, you're a friend?"
    }
  },
  beaux: {
    id: 'beaux',
    name: 'Beaux',
    breed: 'Chihuahua',
    trait: 'compact' as const,
    traitDesc: 'Carries extra item in tiny bandana',
    colors: { fur: ['#F5DEB3', '#DEB887', '#D2B48C'], accent: '#ff6b81' },
    personality: ['tough', 'tiny', 'surprisingly brave'] as const,
    lines: {
      intro: "I may be small, but I'm NOT insignificant. And I have a bandana. Look.",
      happy: "*tiny happy yips* I am the best dog. Everyone knows this.",
      scared: "*makes himself look bigger* I'm not scared! I'm just... very alert!",
      hint: "*ears perk up* I can smell it from here. Well, maybe two blocks away.",
      combat: "*barks at volume 11* Who's the boss now?! *is 8 inches tall*",
      foundFriend: "*sniffs* You're big. I'm... I'm not intimidated at all. *is very intimidated*"
    }
  }
}

export const COMPANIONS: Record<string, Companion> = {
  stray_buddy: {
    id: 'stray_buddy',
    name: 'Buddy',
    breed: 'Golden Retriever',
    trait: '🐾 Friendly',
    dialogue: [
      'Woof! Welcome to the park!',
      'Home is where the fence is. Which fence?',
      'I used to live near the big oak tree!',
      'Follow the scent posts — they lead somewhere!',
    ],
    color: '#DAA520',
    accentColor: '#FFD700',
    met: false,
    active: false,
  },
  shelter_dog: {
    id: 'shelter_dog',
    name: 'Rex',
    breed: 'Mixed Breed',
    trait: '🗺️ Navigator',
    dialogue: [
      'I was here a long time ago. I remember the way out.',
      'The kennels... they\'re not so bad if you find a friend.',
      'There\'s a side gate. The guard leaves it unlatched sometimes.',
      'Follow the scent posts — they lead somewhere!',
    ],
    color: '#5a4a3a',
    accentColor: '#8a7a5a',
    met: false,
    active: false,
  },
  park_stray: {
    id: 'park_stray',
    name: 'Luna',
    breed: 'Border Collie',
    trait: '🧠 Smart',
    dialogue: [
      'I can help you find your way. I\'ve been watching things.',
      'The apartment building has a back entrance. Watch for the cat.',
      'I\'ve seen dogs go that way. They came back... mostly okay.',
      'The neighborhood is close. I can feel it in my paws.',
    ],
    color: '#3a3a3a',
    accentColor: '#ffffff',
    met: false,
    active: false,
  },
  neighborhood_dog: {
    id: 'neighborhood_dog',
    name: 'Max',
    breed: 'Labrador Retriever',
    trait: '🦴 Finder',
    dialogue: [
      'I live nearby! Well, I lived nearby. Now I visit.',
      'This is my old neighborhood. I know every squirrel.',
      'The house with the golden gate? That\'s the one!',
      'My human used to bring me here. It was the best.',
    ],
    color: '#B8860B',
    accentColor: '#DAA520',
    met: false,
    active: false,
  },
  alley_cat_friendly: {
    id: 'alley_cat_friendly',
    name: 'Whiskers',
    breed: 'Cat',
    trait: '👁️ Watcher',
    dialogue: [
      'Dogs. Always dogs. But... you seem nice.',
      'I\'ve seen things from the rooftops. Things you couldn\'t imagine.',
      'The shelter has a back exit. But the cat guard is fierce.',
      'If you want to find home, follow the smells. Cats don\'t forget.',
    ],
    color: '#6a6a6a',
    accentColor: '#9a9a9a',
    met: false,
    active: false,
  },
  // New companions from new zones
  lake_dog: {
    id: 'lake_dog',
    name: 'River',
    breed: 'Nova Scotia Duck Tolling Retriever',
    trait: '🏊 Swimmer',
    dialogue: [
      'The lake is beautiful this time of year!',
      'I used to swim here every day with my human.',
      'There\'s a secret path behind the waterfall. Want to see?',
      'Follow the water — it leads somewhere special.',
    ],
    color: '#D2691E',
    accentColor: '#FFD700',
    met: false,
    active: false,
  },
  pet_shop_dog: {
    id: 'pet_shop_dog',
    name: 'Coco',
    breed: 'Poodle',
    trait: '✨ Groomed',
    dialogue: [
      'Oh my! You\'re so scruffy! Let me help!',
      'I know all the best treats in town!',
      'The dog show is coming up! Want to enter?',
      'My human takes me to the pet shop every week!',
    ],
    color: '#FFB6C1',
    accentColor: '#FF69B4',
    met: false,
    active: false,
  },
  dog_show_dog: {
    id: 'dog_show_dog',
    name: 'Champion',
    breed: 'Standard Poodle',
    trait: '🏆 Champion',
    dialogue: [
      'I\'ve won every dog show in the region!',
      'Would you like to compete? I can train you!',
      'The secret to winning is confidence and treats!',
      'Follow the crowd — they all head to the park!',
    ],
    color: '#FFFFFF',
    accentColor: '#FFD700',
    met: false,
    active: false,
  },
  forest_dog: {
    id: 'forest_dog',
    name: 'Forest',
    breed: 'German Shorthaired Pointer',
    trait: '🌲 Hunter',
    dialogue: [
      'The forest is vast and full of wonders!',
      'I can smell home from here! Well, almost.',
      'Watch out for the storm drain ahead!',
      'The cave behind the waterfall holds secrets.',
    ],
    color: '#8B4513',
    accentColor: '#D2691E',
    met: false,
    active: false,
  },
  beach_dog: {
    id: 'beach_dog',
    name: 'Surfer',
    breed: 'Australian Shepherd',
    trait: '🏄 Surfer',
    dialogue: [
      'The beach is my happy place!',
      'I found a treasure map here once! Want to see?',
      'The waves bring all sorts of interesting things.',
      'Follow the seagulls — they know where the good stuff is!',
    ],
    color: '#4682B4',
    accentColor: '#87CEEB',
    met: false,
    active: false,
  },
  mountain_dog: {
    id: 'mountain_dog',
    name: 'Peak',
    breed: 'Bernese Mountain Dog',
    trait: '⛰️ Climber',
    dialogue: [
      'The mountain path is steep but worth it!',
      'I\'ve seen dogs go up there and come back with stories.',
      'The cave at the top holds ancient treasures.',
      'Watch your step on the rocky paths!',
    ],
    color: '#2F4F4F',
    accentColor: '#708090',
    met: false,
    active: false,
  },
  garden_dog: {
    id: 'garden_dog',
    name: 'Blossom',
    breed: 'Cavalier King Charles Spaniel',
    trait: '🌸 Gentle',
    dialogue: [
      'The garden is so beautiful this time of year!',
      'I love collecting flowers for my nest.',
      'There\'s a secret passage behind the rose bush!',
      'Follow the scent of lavender — it leads home.',
    ],
    color: '#8B0000',
    accentColor: '#FF6347',
    met: false,
    active: false,
  },
  library_dog: {
    id: 'library_dog',
    name: 'Bookworm',
    breed: 'Basenji',
    trait: '📚 Scholar',
    dialogue: [
      'I love the library! So many stories to discover.',
      'There\'s a hidden passage behind the bookshelf!',
      'The librarian dog knows all the secrets of the neighborhood.',
      'Follow the scent of old paper — it leads somewhere special.',
    ],
    color: '#D2B48C',
    accentColor: '#8B4513',
    met: false,
    active: false,
  },
  market_dog: {
    id: 'market_dog',
    name: 'Baker',
    breed: 'Bichon Frise',
    trait: '🍪 Baker',
    dialogue: [
      'I bake the best treats in town!',
      'Want to learn my secret recipe? It\'s simple!',
      'The market has all sorts of interesting smells.',
      'Follow the aroma of fresh bread — it leads to the pet shop!',
    ],
    color: '#FFF8DC',
    accentColor: '#FFD700',
    met: false,
    active: false,
  },
  park_secret_dog: {
    id: 'park_secret_dog',
    name: 'Shadow',
    breed: 'Belgian Malinois',
    trait: '🌙 Stealth',
    dialogue: [
      'I know all the secret paths in the park.',
      'There\'s a hidden treasure behind the old oak tree.',
      'The moon bone only appears at night. Want to wait?',
      'Follow the shadows — they lead to the lake.',
    ],
    color: '#1a1a1a',
    accentColor: '#4a4a4a',
    met: false,
    active: false,
  },
}

export const ZONES: Record<string, Zone> = {
  suburban_streets: {
    id: 'suburban_streets',
    name: '🏘️ Suburban Streets',
    desc: 'Wide sidewalks, unfamiliar houses. The world is so big.',
    type: 'tp', // top-down open world — free-roam hub, same engine as dog park
    skyColor: '#a8d8f0',
    groundColor: '#5c8a4e',
    dogColor: '#d4a574',
    accentColor: '#ff6b35',
    obstacles: [
      // Tree-lined boulevard along the top (the "North Street")
      { type: 'tree', x: -12, z: -7, height: 3, trunkColor: '#5a3a1a', leafColor: '#2d5a1e' },
      { type: 'tree', x: -6, z: -7, height: 3, trunkColor: '#5a3a1a', leafColor: '#3a7a2e' },
      { type: 'tree', x: 0, z: -7, height: 3, trunkColor: '#5a3a1a', leafColor: '#2d6a1e' },
      { type: 'tree', x: 6, z: -7, height: 3, trunkColor: '#5a3a1a', leafColor: '#3a8a2e' },
      { type: 'tree', x: 12, z: -7, height: 3, trunkColor: '#5a3a1a', leafColor: '#2d5a1e' },
      // Front-yard houses & hedges (kept away from the spawn point)
      { type: 'fence', x: -8, z: -2, width: 5, height: 1.2, color: '#8B4513' },
      { type: 'bench', x: -5, z: 4, width: 2, color: '#8B6914' },
      { type: 'tree', x: -10, z: 3, height: 2.5, trunkColor: '#5a3a1a', leafColor: '#3a7a2e' },
      // Alley bushes (shelter, west)
      { type: 'bush', x: -9, z: -4, color: '#2d5a1e' },
      { type: 'tree', x: -12, z: -2, height: 2.5, trunkColor: '#5a3a1a', leafColor: '#2d5a1e' },
      // Pet store garden (north)
      { type: 'bush', x: 2, z: -6, color: '#3a8a2e' },
      { type: 'bush', x: -2, z: -6, color: '#2d6a1e' },
      // Garden flowers (east)
      { type: 'bush', x: 10, z: 1, color: '#ff6f91' },
      { type: 'bush', x: 12, z: 2, color: '#2d6a1e' },
      // Library lawn (east)
      { type: 'tree', x: 11, z: -2, height: 2.5, trunkColor: '#5a3a1a', leafColor: '#3a7a2e' },
      { type: 'bush', x: 9, z: -1, color: '#2d6a1e' },
      // Market stalls (south)
      { type: 'bench', x: -1, z: 8, width: 2, color: '#8B6914' },
      { type: 'bush', x: 3, z: 8, color: '#3a8a2e' },
      { type: 'tree', x: -5, z: 10, height: 3, trunkColor: '#5a3a1a', leafColor: '#2d5a1e' },
      // Dog show grandstand (north)
      { type: 'bench', x: 9, z: -6, width: 3, color: '#8B6914' },
      { type: 'bush', x: 12, z: -7, color: '#3a8a2e' },
      // Lake shoreline (north)
      { type: 'bush', x: -10, z: -8, color: '#3a8a2e' },
      { type: 'tree', x: -13, z: -9, height: 3, trunkColor: '#5a3a1a', leafColor: '#2d6a1e' },
      // Forest edge (east)
      { type: 'tree', x: 13, z: -4, height: 3, trunkColor: '#5a3a1a', leafColor: '#1e4a12' },
      { type: 'tree', x: 15, z: -3, height: 2.5, trunkColor: '#5a3a1a', leafColor: '#2d6a1e' },
      { type: 'bush', x: 14, z: -2, color: '#1e4a12' },
      // Beach palm (south)
      { type: 'tree', x: -3, z: 12, height: 3, trunkColor: '#a0722d', leafColor: '#3a8a2e' },
      { type: 'bush', x: 1, z: 13, color: '#3a8a2e' },
      // Mountain path pine (south)
      { type: 'tree', x: -9, z: 12, height: 3, trunkColor: '#5a3a1a', leafColor: '#1e4a12' },
      { type: 'tree', x: -11, z: 13, height: 2.5, trunkColor: '#5a3a1a', leafColor: '#2d6a1e' },
      // Waterfall mossy rocks (east)
      { type: 'bush', x: 12, z: 5, color: '#2d5a1e' },
      { type: 'bush', x: 14, z: 6, color: '#3a8a2e' },
      // Secret park shadows (deep east)
      { type: 'tree', x: 16, z: 4, height: 3, trunkColor: '#3a2a1a', leafColor: '#1a3a12' },
      { type: 'tree', x: 17, z: 6, height: 2.5, trunkColor: '#3a2a1a', leafColor: '#142e0e' },
      { type: 'bush', x: 15, z: 5, color: '#1a3a12' }
    ],
    npcs: [
      {
        id: 'mailman_dog',
        name: 'Biscuit',
        color: '#D2A679',
        accentColor: '#C68642',
        x: 3,
        z: 3,
        dialogue: [
          'Woof! You\'re a long way from home, friend.',
          'I\'ve seen a lot of dogs pass through these streets.',
          'The lake\'s a nice place to think. And the forest, if you like.',
        ],
      },
      {
        id: 'squirrel_spotter',
        name: 'Pip',
        color: '#A0522D',
        accentColor: '#CD853F',
        x: -4,
        z: 1,
        dialogue: [
          'SQUIRREL! Right over by the hedges!',
          '...okay, it went in a tree. Classic squirrel.',
          'Hey, have you been to the garden? Best tomatoes in the county.',
        ],
      },
    ],
    features: [
      // Player starts in the front yard
      { type: 'here', x: 0, z: 0, id: 'street_start', label: '🐾 You Are Here' },
      // Item pickups (spread around the hub so they're easy to find)
      { type: 'treasure', x: 3, z: 4, id: 'street_bone', label: '🦴 Bone', item: 'bone' },
      { type: 'treasure', x: -4, z: 6, id: 'street_treat', label: '🍖 Treat', item: 'treat' },
      { type: 'hint', x: -8, z: -4, id: 'street_map', label: '🐾 Scent Mark', item: 'map_fragment' },
      { type: 'treasure', x: 7, z: -4, id: 'street_ticket', label: '🎫 Pet Shop Scent', item: 'pet_shop_ticket' },
      { type: 'treasure', x: 15, z: -5, id: 'street_pinecone', label: '🌲 Trail Mark', item: 'pinecone' },
      { type: 'mailbox', x: -11, z: -8, id: 'street_icecream', label: '🍦 Ice Cream Truck', threat: 'ice_cream_truck' },
      { type: 'treasure', x: -9, z: 12, id: 'street_compass', label: '🗺️ Trail', item: 'compass_fragment' },
      { type: 'treasure', x: 14, z: 7, id: 'street_stone', label: '💧 Splash', item: 'lake_stone' },
      // Threats (kept from the old rooms + zone-specific)
      { type: 'traffic', x: 11, z: -6, id: 'street_traffic', label: '🚗 Traffic' },
      { type: 'cat', x: -12, z: -4, id: 'street_cat', label: '🐱 Mean Cat' },
      { type: 'mailbox', x: -10, z: 8, id: 'street_mail', label: '📬 Mail Carrier', threat: 'mailman' },
      { type: 'trap', x: 12, z: 10, id: 'street_construction', label: '🚧 Construction Crew', threat: 'construction' },
      // Gates to every other zone (spread around the hub)
      { type: 'gate', x: 8, z: 3, id: 'gate_dog_park', label: '🌳 Dog Park', gate: 'dog_park' },
      { type: 'gate', x: -15, z: -2, id: 'gate_shelter', label: '🏥 Shelter', gate: 'shelter' },
      { type: 'gate', x: -7, z: 3, id: 'gate_apartment', label: '🏢 Apartment', gate: 'apartment' },
      { type: 'gate', x: 4, z: -10, id: 'gate_pet_store', label: '🛒 Pet Store', gate: 'pet_store' },
      { type: 'gate', x: 13, z: 2, id: 'gate_garden', label: '🌷 Garden', gate: 'garden' },
      { type: 'gate', x: 13, z: -3, id: 'gate_library', label: '📚 Library', gate: 'library' },
      { type: 'gate', x: 1, z: 12, id: 'gate_market', label: '🧺 Market', gate: 'market' },
      { type: 'gate', x: 11, z: -9, id: 'gate_dog_show', label: '🏅 Dog Show', gate: 'dog_show' },
      { type: 'gate', x: -14, z: -11, id: 'gate_lake', label: '🌊 Lake', gate: 'lake' },
      { type: 'gate', x: 16, z: -5, id: 'gate_forest', label: '🌲 Forest', gate: 'forest' },
      { type: 'gate', x: -3, z: 15, id: 'gate_beach', label: '🏖️ Beach', gate: 'beach' },
      { type: 'gate', x: -12, z: 14, id: 'gate_mountain', label: '⛰️ Mountain', gate: 'mountain' },
      { type: 'gate', x: 16, z: 7, id: 'gate_waterfall', label: '💦 Waterfall', gate: 'waterfall' },
      { type: 'gate', x: 18, z: 4, id: 'gate_secret', label: '🌙 Secret Park', gate: 'park_secret' },
    
      { type: 'treasure', x: 5, z: 5, id: 'suburban_streets_key', label: '✨ key', item: 'key' },
      { type: 'treasure', x: 5, z: 5, id: 'suburban_streets_dog_license', label: '✨ dog_license', item: 'dog_license' },
      { type: 'treasure', x: 5, z: 5, id: 'suburban_streets_collar_piece', label: '✨ collar_piece', item: 'collar_piece' },
      { type: 'treasure', x: 5, z: 5, id: 'suburban_streets_water_bottle', label: '✨ water_bottle', item: 'water_bottle' },],
    music: 'suburban',
    hint: 'You see a squirrel. It reminds you of... something. A yard? With squirrels? The gates all lead somewhere — follow the one that smells like home.'
  },
  dog_park: {
    threat: 'ice_cream_truck',
    threatKind: 'comfort',
    id: 'dog_park',
    transition: 'slide',
    name: '🌳 Dog Park',
    desc: 'A bright, open space. Other dogs are everywhere!',
    type: 'tp',
    music: 'dog_park',
    skyColor: '#87CEEB',
    groundColor: '#4a7c3f',
    dogColor: '#d4a574',
    accentColor: '#ff6b35',
    companions: ['stray_buddy'],
    obstacles: [
      { type: 'fence', x: -8, z: -6, width: 6, height: 1.2, color: '#8B4513' },
      { type: 'fence', x: 8, z: 6, width: 5, height: 1.2, color: '#8B4513', rotation: Math.PI / 4 },
      { type: 'tree', x: -4, z: 3, height: 3, trunkColor: '#5a3a1a', leafColor: '#2d5a1e' },
      { type: 'tree', x: 5, z: -4, height: 2.5, trunkColor: '#5a3a1a', leafColor: '#3a7a2e' },
      { type: 'bench', x: 3, z: 5, width: 2, color: '#8B6914' },
      { type: 'bush', x: -6, z: -3, color: '#2d6a1e' },
      { type: 'bush', x: 7, z: -1, color: '#3a8a2e' },
    ],
    npcs: [
      {
        id: 'golden_retriever',
        name: 'Buddy',
        color: '#DAA520',
        accentColor: '#FFD700',
        x: 2,
        z: -3,
        dialogue: [
          'Woof! Welcome to the park!',
          'Home is where the fence is. Which fence?',
          'I used to live near the big oak tree!',
          'Follow the scent posts — they lead somewhere!',
        ],
      },
      {
        id: 'dog_walker',
        name: 'Sarah',
        color: '#5a7a9a',
        accentColor: '#4a9eff',
        x: -3,
        z: 4,
        dialogue: [
          'Hi there, sweetie! Are you lost?',
          'Have you seen a husky around here?',
          'The shelter is this way! *points*',
        ],
      },

      {
        id: 'luna_npc',
        name: 'Luna',
        color: '#3a3a3a',
        accentColor: '#ffffff',
        x: -2,
        z: 6,
        dialogue: [
          'I can help you find your way. I\'ve been watching things.',
          'The apartment building has a back entrance. Watch for the cat.',
        ],
      },
      {
        id: 'whiskers_npc',
        name: 'Whiskers',
        color: '#6a6a6a',
        accentColor: '#9a9a9a',
        x: 5,
        z: -5,
        dialogue: [
          'Dogs. Always dogs. But... you seem nice.',
          'The shelter has a back exit. But the cat guard is fierce.',
        ],
      },
    ],
    features: [
      { type: 'water_bowl', x: 6, z: 3, id: 'water_bowl', label: '💧 Water Bowl' },
      { type: 'mailbox', x: -6, z: 6, id: 'park_hydrant', label: '🚒 Storm Drain', threat: 'storm_sewer' },
      { type: 'fire_hydrant', x: -5, z: -2, id: 'fire_hydrant', label: '🚒 Fire Hydrant' },
      { type: 'scent_post', x: 0, z: 7, id: 'scent_post', label: '🐾 Scent Post' },
      { type: 'treasure', x: -7, z: 5, id: 'treasure_1', label: '✨ Scent Clue' },
      { type: 'mailbox', x: 5, z: 5, id: 'park_squirrel', label: '🐿️ Squirrel Army', threat: 'park_squirrel' },
      { type: 'return_gate', x: 0, z: -8, id: 'park_exit', label: '🚪 Exit to Streets' },
    
      { type: 'treasure', x: 5, z: 5, id: 'dog_park_favorite_toy', label: '✨ favorite_toy', item: 'favorite_toy' },
      { type: 'treasure', x: 5, z: 5, id: 'dog_park_warm_blanket', label: '✨ warm_blanket', item: 'warm_blanket' },
      { type: 'treasure', x: 5, z: 5, id: 'dog_park_golden_bone', label: '✨ golden_bone', item: 'golden_bone' },
      { type: 'treasure', x: 5, z: 5, id: 'dog_park_comfort_bell', label: '✨ comfort_bell', item: 'comfort_bell' },],
    returnZone: 'suburban_streets',
    hint: 'A big dog says "Home is where the fence is." Fences are everywhere... but which fence?',
  },
  apartment: {
    threat: 'storm',
    threatKind: 'comfort',
    id: 'apartment',
    transition: 'wipe',
    name: '🏠 Random Apartment',
    desc: 'You found the door open. Inside: smells, sounds, and a TV that barks back.',
    type: 'fp',
    rooms: [
      { id: 'apt_entrance', name: 'Entryway', w: 120, h: 80, d: 150, color: '#8a7a6a', exits: ['apt_living', 'apt_kitchen'], isEntrance: true, entranceZone: 'suburban_streets' },
      { id: 'apt_living', name: 'Living Room', w: 200, h: 100, d: 180, color: '#7a6a5a', exits: ['apt_entrance', 'apt_bedroom'], features: [{type:'tv', x:100, y:50, w:60, h:40, label:'📺 TV (barks back)'}, { type: 'treasure', x: 50, y: 50, w: 40, h: 30, label: '✨ blanket', item: 'blanket' }, { type: 'treasure', x: 50, y: 50, w: 40, h: 30, label: '✨ home_photo', item: 'home_photo' }, { type: 'treasure', x: 50, y: 50, w: 40, h: 30, label: '✨ diary_page', item: 'diary_page' }, { type: 'treasure', x: 50, y: 50, w: 40, h: 30, label: '✨ squirrel_dog', item: 'squirrel_dog' },] },
      { id: 'apt_kitchen', name: 'Kitchen', w: 150, h: 90, d: 120, color: '#9a8a7a', exits: ['apt_entrance', 'apt_bathroom'], features: [{type:'food', x:75, y:45, w:40, h:30, label:'🍖 Food', item:'treat'}] },
      { id: 'apt_bedroom', name: 'Bedroom', w: 160, h: 90, d: 140, color: '#6a5a7a', exits: ['apt_living', 'apt_bathroom'], features: [{type:'hint', x:80, y:45, w:50, h:30, label:'🧸 Toy', item:'toy'}] },
      { id: 'apt_bathroom', name: 'Bathroom', w: 100, h: 80, d: 100, color: '#8a8a9a', exits: ['apt_kitchen', 'apt_bedroom'], features: [{type:'water_bowl', x:50, y:40, w:30, h:30, label:'💧 Water Bowl'}] },
      { id: 'apt_balcony', name: 'Balcony', w: 120, h: 70, d: 80, color: '#5a7a5a', exits: ['apt_living'], features: [{type:'hint', x:60, y:35, w:40, h:30, label:'🌳 View', item:'tree_clue'}] }
    ],
    music: 'apartment',
    hint: 'Under the bed: a red ball. You remember throwing this. Someone threw this. For YOU.',
    returnZone: 'suburban_streets',
  },
  shelter: {
    threat: 'vacuum',
    threatKind: 'sneak',
    id: 'shelter',
    transition: 'fade',
    name: '🏥 Animal Shelter',
    desc: 'Cages, sounds, and hope. Maybe some dogs here know the way home.',
    type: 'fp',
    rooms: [
      { id: 'shelter_lobby', name: 'Lobby', w: 200, h: 100, d: 150, color: '#8a8a9a', exits: ['shelter_kennels', 'shelter_office', 'shelter_exit', 'shelter_garden'] },
      { id: 'shelter_exit', name: 'Exit Door', w: 80, h: 60, d: 80, color: '#6a6a7a', exits: ['shelter_lobby', 'shelter_to_neighborhood'] },
      { id: 'shelter_to_neighborhood', name: 'Side Gate', w: 60, h: 50, d: 60, color: '#5a5a6a', exits: ['shelter_lobby'], isEntrance: true, entranceZone: 'neighborhood' },
      { id: 'shelter_kennels', name: 'Kennels', w: 300, h: 120, d: 200, color: '#7a7a8a', exits: ['shelter_lobby'], features: [{type:'dog_friend', x:150, y:60, w:50, h:40, label:'🐕 New Friend', item:'friend'}, { type: 'treasure', x: 50, y: 50, w: 40, h: 30, label: '✨ collar_buckle', item: 'collar_buckle' }, { type: 'treasure', x: 50, y: 50, w: 40, h: 30, label: '✨ leash', item: 'leash' }, { type: 'treasure', x: 50, y: 50, w: 40, h: 30, label: '✨ treat_bag', item: 'treat_bag' }, { type: 'treasure', x: 50, y: 50, w: 40, h: 30, label: '✨ magic_bone', item: 'magic_bone' },] },
      { id: 'shelter_office', name: 'Office', w: 120, h: 80, d: 100, color: '#6a6a7a', exits: ['shelter_lobby'], features: [{type:'hint', x:60, y:40, w:40, h:30, label:'📋 Poster', item:'map_fragment'}] },
      { id: 'shelter_garden', name: 'Garden', w: 150, h: 100, d: 120, color: '#4a7a3a', exits: ['shelter_lobby'], features: [{type:'food', x:75, y:50, w:40, h:30, label:'🍖 Treat', item:'treat'}] },
      { id: 'shelter_vet', name: 'Vet Room', w: 100, h: 80, d: 100, color: '#9a9aaa', exits: ['shelter_lobby'], features: [{type:'hint', x:50, y:40, w:40, h:30, label:'📋 Medical Record', item:'collar'}] }
    ],
    companions: ['shelter_dog'],
    music: 'shelter',
    hint: 'A poster shows a lost dog. It looks... familiar. But it could be anyone.',
    returnZone: 'suburban_streets',
  },
  neighborhood: {
    threat: 'bully',
    features: [
      { type: 'trap', x: 8, z: 6, id: 'neighbor_dog_feature', label: '🐕 Neighbor Dog', threat: 'neighbor_dog' },
    ],
    threatKind: 'combat',
    id: 'neighborhood',
    transition: 'slide',
    name: '🏡 The Neighborhood',
    desc: 'The streets feel familiar. You\'re close. You can feel it.',
    type: 'fp',
    rooms: [
      { id: 'neighborhood_entrance', name: 'Side Gate', w: 80, h: 60, d: 80, color: '#5a5a5a', exits: ['neighborhood_start'], isEntrance: true, entranceZone: 'shelter' },
      { id: 'neighborhood_start', name: 'Street Corner', w: 250, h: 120, d: 200, color: '#5a8a5a', exits: ['neighborhood_main', 'neighborhood_park', 'neighborhood_entrance', 'neighborhood_library'] },
      { id: 'neighborhood_main', name: 'Main Street', w: 350, h: 140, d: 300, color: '#6a6a6a', exits: ['neighborhood_start', 'neighborhood_home', 'neighborhood_market'], features: [{type:'person', x:175, y:70, w:40, h:60, label:'👤 "Have you seen a dog like him?"'}, { type: 'treasure', x: 50, y: 50, w: 40, h: 30, label: '✨ medal', item: 'medal' }, { type: 'treasure', x: 50, y: 50, w: 40, h: 30, label: '✨ bone_necklace', item: 'bone_necklace' }, { type: 'treasure', x: 50, y: 50, w: 40, h: 30, label: '✨ tennis_ball', item: 'tennis_ball' }, { type: 'treasure', x: 50, y: 50, w: 40, h: 30, label: '✨ dog_tag', item: 'dog_tag' }, {type:'dog_friend', x:120, y:60, w:50, h:40, label:'🐕 Max the Neighborhood Dog', companion:'neighborhood_dog'}] },
      { id: 'neighborhood_park', name: 'Local Park', w: 200, h: 100, d: 180, color: '#4a7a3a', exits: ['neighborhood_start'], features: [{type:'hint', x:100, y:50, w:60, h:30, label:'🌳 Old Tree', item:'tree_clue'}] },
      { id: 'neighborhood_home', name: 'The House', w: 180, h: 100, d: 150, color: '#8a7a5a', exits: ['neighborhood_main'], isHome: true, isEntrance: true, entranceZone: 'home', features: [{type:'home', x:90, y:50, w:60, h:60, label:'🏠 Home'}] },
      { id: 'neighborhood_library', name: 'Library', w: 140, h: 90, d: 120, color: '#7a6a5a', exits: ['neighborhood_start'], features: [{type:'hint', x:70, y:45, w:50, h:30, label:'📚 Lost Dog Poster', item:'photo'}] },
      { id: 'neighborhood_market', name: 'Market', w: 200, h: 110, d: 160, color: '#8a7a4a', exits: ['neighborhood_main'], features: [{type:'food', x:100, y:55, w:50, h:30, label:'🍖 Food Stand', item:'treat'}] }
    ],
    music: 'home',
    hint: 'The gate. It\'s the same gate. You remember this one. This is it.',
    returnZone: 'suburban_streets',
  },
  home: {
    threat: 'earthquake',
    threatKind: 'timing',
    id: 'home',
    transition: 'zoom',
    name: '🏡 Home',
    desc: 'You made it! The golden gate stands before you. This is where you belong.',
    type: 'fp',
    rooms: [
      { id: 'home_gate', name: 'Golden Gate', w: 100, h: 80, d: 80, color: '#d4a017', exits: ['home_yard'], isEntrance: true, entranceZone: 'neighborhood' },
      { id: 'home_yard', name: 'Backyard', w: 250, h: 150, d: 200, color: '#4a8a3a', exits: ['home_gate', 'home_door'], features: [{type:'celebration', x:125, y:75, w:80, h:60, label:'🎉 Welcome Home!'}] },
      { id: 'home_door', name: 'Front Door', w: 80, h: 100, d: 60, color: '#8a6a3a', exits: ['home_yard'], isHome: true, features: [{type:'home', x:40, y:50, w:60, h:60, label:'🏠 Home'}] }
    ],
    music: 'home',
    hint: 'You\'re home. You\'re finally home.',
    returnZone: 'suburban_streets',
  },
  // New zones
  lake: {
    threat: 'flood',
    threatKind: 'sneak',
    doorThreat: 'lake_ripple',
    id: 'lake',
    transition: 'fade',
    name: '🌊 The Lake',
    desc: 'A peaceful lake surrounded by trees. The water sparkles in the sunlight.',
    type: 'tp',
    music: 'lake',
    skyColor: '#87CEEB',
    groundColor: '#2d5a1e',
    dogColor: '#4a9eff',
    accentColor: '#006994',
    companions: ['lake_dog'],
    obstacles: [
      { type: 'tree', x: -5, z: 4, height: 4, trunkColor: '#5a3a1a', leafColor: '#2d5a1e' },
      { type: 'tree', x: 6, z: -3, height: 3.5, trunkColor: '#5a3a1a', leafColor: '#3a7a2e' },
      { type: 'bush', x: -7, z: -5, color: '#2d6a1e' },
      { type: 'bench', x: 4, z: 6, width: 2, color: '#8B6914' },
      { type: 'fence', x: 0, z: 8, width: 8, height: 1, color: '#8B4513' },
    ],
    npcs: [
      {
        id: 'lake_dog_npc',
        name: 'River',
        color: '#D2691E',
        accentColor: '#FFD700',
        x: 3,
        z: -2,
        dialogue: [
          'The lake is beautiful this time of year!',
          'I used to swim here every day with my human.',
          'There\'s a secret path behind the waterfall. Want to see?',
          'Follow the water — it leads somewhere special.',
        ],
      },
    ],
    features: [
      { type: 'water', x: 0, z: 0, id: 'lake_center', label: '🌊 Lake Center' },
      { type: 'scent_post', x: -6, z: 5, id: 'lake_scent', label: '🐾 Scent Post' },
      { type: 'treasure', x: 7, z: -6, id: 'lake_treasure', label: '✨ Hidden Treasure' },
      { type: 'trap', x: -6, z: 6, id: 'lake_monster', label: '🐉 Lake Monster', threat: 'lake_monster' },
      { type: 'mailbox', x: 9, z: 8, id: 'lake_fog', label: '🌫️ Thick Fog', threat: 'fog' },
      { type: 'bridge', x: 5, z: 3, id: 'wooden_bridge', label: '🌉 Wooden Bridge' },
      { type: 'return_gate', x: 0, z: -8, id: 'lake_exit', label: '🚪 Exit to Streets' },
    
      { type: 'treasure', x: 5, z: 5, id: 'lake_lake_crystal', label: '✨ lake_crystal', item: 'lake_crystal' },
      { type: 'treasure', x: 5, z: 5, id: 'lake_shiny_rock', label: '✨ shiny_rock', item: 'shiny_rock' },
      { type: 'treasure', x: 5, z: 5, id: 'lake_feather', label: '✨ feather', item: 'feather' },
      { type: 'treasure', x: 5, z: 5, id: 'lake_leaf', label: '✨ leaf', item: 'leaf' },],
    returnZone: 'suburban_streets',
    hint: 'The water sparkles. You remember swimming here once. With your human.',
  },
  pet_store: {
    threat: 'pet_shop_bell',
    threatKind: 'timing',
    features: [
      { type: 'trap', x: 7, z: -6, id: 'petshop_cat_feature', label: '🐱 Pet Shop Cat', threat: 'pet_shop_cat' },
    ],
    id: 'pet_store',
    transition: 'wipe',
    name: '🏪 Pet Paradise',
    desc: 'A colorful pet shop filled with treats, toys, and friendly animals.',
    type: 'fp',
    rooms: [
      { id: 'pet_entrance', name: 'Entrance', w: 120, h: 80, d: 150, color: '#FFB6C1', exits: ['pet_main', 'pet_back'], isEntrance: true, entranceZone: 'suburban_streets' },
      { id: 'pet_main', name: 'Main Hall', w: 200, h: 100, d: 180, color: '#FF69B4', exits: ['pet_entrance', 'pet_treats', 'pet_toys', 'pet_grooming'], features: [{type:'pet_shop', x:100, y:50, w:60, h:40, label:'🏪 Pet Paradise'}, { type: 'treasure', x: 50, y: 50, w: 40, h: 30, label: '✨ companion_treat', item: 'companion_treat' }, { type: 'treasure', x: 50, y: 50, w: 40, h: 30, label: '✨ companion_toy', item: 'companion_toy' }, { type: 'treasure', x: 50, y: 50, w: 40, h: 30, label: '✨ golden_treat', item: 'golden_treat' }, { type: 'treasure', x: 50, y: 50, w: 40, h: 30, label: '✨ ice_cream', item: 'ice_cream' }, {type:'dog_friend', x:120, y:60, w:50, h:40, label:'🐕 Coco at Pet Paradise', companion:'pet_shop_dog'}] },
      { id: 'pet_treats', name: 'Treat Room', w: 150, h: 90, d: 120, color: '#FFD700', exits: ['pet_main'], features: [{type:'food', x:75, y:45, w:40, h:30, label:'🍪 Treats', item:'pet_shop_treat'}] },
      { id: 'pet_toys', name: 'Toy Room', w: 160, h: 90, d: 140, color: '#FF69B4', exits: ['pet_main'], features: [{type:'hint', x:80, y:45, w:50, h:30, label:'🧸 Toys', item:'pet_shop_ticket'}] },
      { id: 'pet_grooming', name: 'Grooming Room', w: 100, h: 80, d: 100, color: '#FFF0F5', exits: ['pet_main'], features: [{type:'water', x:50, y:40, w:30, h:30, label:'💧 Water Bowl'}] },
      { id: 'pet_back', name: 'Back Room', w: 120, h: 70, d: 80, color: '#FFB6C1', exits: ['pet_entrance'], features: [{type:'secret_passage', x:60, y:35, w:40, h:30, label:'🔑 Secret Passage', item:'secret_key'}] }
    ],
    music: 'pet_store',
    hint: 'The smell of treats is overwhelming. Your human used to bring you here!',
  },
  dog_show: {
    threat: 'dog_show_judge',
    threatKind: 'timing',
    doorThreat: 'dog_show_roar',
    id: 'dog_show',
    transition: 'zoom',
    name: '🏆 Dog Show Arena',
    desc: 'A grand arena where dogs compete for glory. The air is filled with excitement.',
    type: 'tp',
    music: 'dog_show',
    skyColor: '#87CEEB',
    groundColor: '#8B4513',
    dogColor: '#FFD700',
    accentColor: '#FF6347',
    companions: ['dog_show_dog'],
    obstacles: [
      { type: 'fence', x: -10, z: -8, width: 8, height: 1.5, color: '#8B4513' },
      { type: 'fence', x: 10, z: 8, width: 8, height: 1.5, color: '#8B4513' },
      { type: 'tree', x: -6, z: 5, height: 4, trunkColor: '#5a3a1a', leafColor: '#2d5a1e' },
      { type: 'tree', x: 7, z: -6, height: 3.5, trunkColor: '#5a3a1a', leafColor: '#3a7a2e' },
      { type: 'bench', x: 5, z: 7, width: 3, color: '#8B6914' },
      { type: 'bench', x: -8, z: -5, width: 3, color: '#8B6914' },
    ],
    npcs: [
      {
        id: 'dog_show_dog_npc',
        name: 'Champion',
        color: '#FFFFFF',
        accentColor: '#FFD700',
        x: 2,
        z: -3,
        dialogue: [
          'I\'ve won every dog show in the region!',
          'Would you like to compete? I can train you!',
          'The secret to winning is confidence and treats!',
          'Follow the crowd — they all head to the park!',
        ],
      },
    ],
    features: [
      { type: 'dog_show', x: 0, z: 0, id: 'show_ring', label: '🏆 Show Ring' },
      { type: 'scent_post', x: -8, z: 6, id: 'show_scent', label: '🐾 Scent Post' },
      { type: 'treasure', x: 9, z: -7, id: 'show_treasure', label: '✨ Trophy Case' },
      { type: 'mailbox', x: -8, z: -6, id: 'show_roar', label: '📢 Roaring Crowd', threat: 'dog_show_roar' },
      { type: 'lure', x: 6, z: 4, id: 'treat_lure', label: '🍖 Treat Lure' },
      { type: 'return_gate', x: 0, z: -8, id: 'show_exit', label: '🚪 Exit to Streets' },
    
      { type: 'treasure', x: 5, z: 5, id: 'dog_show_dog_show_trophy', label: '✨ dog_show_trophy', item: 'dog_show_trophy' },
      { type: 'treasure', x: 5, z: 5, id: 'dog_show_rainbow_ribbon', label: '✨ rainbow_ribbon', item: 'rainbow_ribbon' },
      { type: 'treasure', x: 5, z: 5, id: 'dog_show_puzzle_piece', label: '✨ puzzle_piece', item: 'puzzle_piece' },
      { type: 'treasure', x: 5, z: 5, id: 'dog_show_moon_bone', label: '✨ moon_bone', item: 'moon_bone' },],
    returnZone: 'suburban_streets',
    hint: 'The roar of the crowd excites you. You remember winning here once.',
  },
  forest: {
    threat: 'forest_wolf',
    threatKind: 'combat',
    id: 'forest',
    transition: 'wipe',
    name: '🌲 The Deep Forest',
    desc: 'A dense forest with towering trees. Sunlight filters through the canopy.',
    type: 'tp',
    music: 'forest',
    skyColor: '#2F4F4F',
    groundColor: '#1a3a0a',
    dogColor: '#8B4513',
    accentColor: '#D2691E',
    companions: ['forest_dog'],
    obstacles: [
      { type: 'tree', x: -8, z: 6, height: 5, trunkColor: '#5a3a1a', leafColor: '#1a3a0a' },
      { type: 'tree', x: 7, z: -5, height: 4.5, trunkColor: '#5a3a1a', leafColor: '#2d5a1e' },
      { type: 'tree', x: -3, z: -7, height: 4, trunkColor: '#5a3a1a', leafColor: '#3a7a2e' },
      { type: 'bush', x: 6, z: 7, color: '#2d6a1e' },
      { type: 'bush', x: -7, z: -6, color: '#3a8a2e' },
      { type: 'fence', x: 0, z: 9, width: 6, height: 1.2, color: '#8B4513' },
    ],
    npcs: [
      {
        id: 'forest_dog_npc',
        name: 'Forest',
        color: '#8B4513',
        accentColor: '#D2691E',
        x: -2,
        z: 4,
        dialogue: [
          'The forest is vast and full of wonders!',
          'I can smell home from here! Well, almost.',
          'Watch out for the storm drain ahead!',
          'The cave behind the waterfall holds secrets.',
        ],
      },
    ],
    features: [
      { type: 'fountain', x: 0, z: 0, id: 'forest_fountain', label: '💧 Forest Spring' },
      { type: 'scent_post', x: -9, z: 7, id: 'forest_scent', label: '🐾 Scent Post' },
      { type: 'trap', x: -8, z: -5, id: 'forest_thorn', label: '🌵 Forest Thorns', threat: 'forest_thorn' },
      { type: 'mailbox', x: 9, z: 9, id: 'forest_squirrel', label: '🐿️ Squirrel', threat: 'squirrel' },
      { type: 'treasure', x: 8, z: -8, id: 'forest_treasure', label: '✨ Cave Entrance' },
      { type: 'lure', x: 5, z: 6, id: 'forest_lure', label: '🍖 Food Scent' },
      { type: 'return_gate', x: 0, z: -8, id: 'forest_exit', label: '🚪 Exit to Streets' },
      { type: 'cave_entrance', x: 10, z: 0, id: 'cave_path', label: '🕳️ Cave Entrance' },
    
      { type: 'treasure', x: 5, z: 5, id: 'forest_forest_mushroom', label: '✨ forest_mushroom', item: 'forest_mushroom' },
      { type: 'treasure', x: 5, z: 5, id: 'forest_star_bone', label: '✨ star_bone', item: 'star_bone' },
      { type: 'treasure', x: 5, z: 5, id: 'forest_flashlight', label: '✨ flashlight', item: 'flashlight' },
      { type: 'treasure', x: 5, z: 5, id: 'forest_rope', label: '✨ rope', item: 'rope' },],
    returnZone: 'suburban_streets',
    hint: 'The forest smells like home. Your human used to bring you here for walks.',
  },
  beach: {
    threat: 'beach_wave',
    threatKind: 'timing',
    doorThreat: 'beach_crab',
    id: 'beach',
    transition: 'fade',
    name: '🏖️ Sandy Beach',
    desc: 'A wide sandy beach with crashing waves. Seagulls cry overhead.',
    type: 'tp',
    music: 'beach',
    skyColor: '#87CEEB',
    groundColor: '#F4A460',
    dogColor: '#4682B4',
    accentColor: '#87CEEB',
    companions: ['beach_dog'],
    obstacles: [
      { type: 'tree', x: -6, z: 5, height: 3, trunkColor: '#5a3a1a', leafColor: '#2d5a1e' },
      { type: 'tree', x: 7, z: -4, height: 2.5, trunkColor: '#5a3a1a', leafColor: '#3a7a2e' },
      { type: 'bush', x: -8, z: -6, color: '#2d6a1e' },
      { type: 'bench', x: 4, z: 7, width: 2, color: '#8B6914' },
    ],
    npcs: [
      {
        id: 'beach_dog_npc',
        name: 'Surfer',
        color: '#4682B4',
        accentColor: '#87CEEB',
        x: 3,
        z: -2,
        dialogue: [
          'The beach is my happy place!',
          'I found a treasure map here once! Want to see?',
          'The waves bring all sorts of interesting things.',
          'Follow the seagulls — they know where the good stuff is!',
        ],
      },
    ],
    features: [
      { type: 'water', x: 0, z: -8, id: 'ocean', label: '🌊 Ocean' },
      { type: 'scent_post', x: -7, z: 6, id: 'beach_scent', label: '🐾 Scent Post' },
      { type: 'treasure', x: 8, z: -7, id: 'beach_treasure', label: '✨ Buried Treasure' },
      { type: 'lure', x: 5, z: 5, id: 'beach_lure', label: '🍖 Fish Scent' },
      { type: 'return_gate', x: 0, z: -8, id: 'beach_exit', label: '🚪 Exit to Streets' },
    
      { type: 'treasure', x: 5, z: 5, id: 'beach_beach_shell', label: '✨ beach_shell', item: 'beach_shell' },
      { type: 'treasure', x: 5, z: 5, id: 'beach_shell', label: '✨ shell', item: 'shell' },
      { type: 'treasure', x: 5, z: 5, id: 'beach_umbrella', label: '✨ umbrella', item: 'umbrella' },
      { type: 'treasure', x: 5, z: 5, id: 'beach_hot_dog', label: '✨ hot_dog', item: 'hot_dog' },],
    returnZone: 'suburban_streets',
    hint: 'The sand feels familiar. Your human used to throw the ball here.',
  },
  mountain: {
    threat: 'mountain_rockfall',
    threatKind: 'timing',
    doorThreat: 'mountain_goat',
    id: 'mountain',
    transition: 'zoom',
    name: '⛰️ Mountain Peak',
    desc: 'A towering mountain with rocky paths. The view from the top is breathtaking.',
    type: 'tp',
    music: 'mountain',
    skyColor: '#4682B4',
    groundColor: '#708090',
    dogColor: '#2F4F4F',
    accentColor: '#708090',
    companions: ['mountain_dog'],
    obstacles: [
      { type: 'tree', x: -7, z: 5, height: 4, trunkColor: '#5a3a1a', leafColor: '#1a3a0a' },
      { type: 'tree', x: 8, z: -6, height: 3.5, trunkColor: '#5a3a1a', leafColor: '#2d5a1e' },
      { type: 'bush', x: -9, z: -7, color: '#2d6a1e' },
      { type: 'fence', x: 0, z: 10, width: 7, height: 1.5, color: '#8B4513' },
    ],
    npcs: [
      {
        id: 'mountain_dog_npc',
        name: 'Peak',
        color: '#2F4F4F',
        accentColor: '#708090',
        x: -3,
        z: 4,
        dialogue: [
          'The mountain path is steep but worth it!',
          'I\'ve seen dogs go up there and come back with stories.',
          'The cave at the top holds ancient treasures.',
          'Watch your step on the rocky paths!',
        ],
      },
    ],
    features: [
      { type: 'fountain', x: 0, z: 0, id: 'mountain_spring', label: '💧 Mountain Spring' },
      { type: 'scent_post', x: -8, z: 7, id: 'mountain_scent', label: '🐾 Scent Post' },
      { type: 'treasure', x: 9, z: -8, id: 'mountain_treasure', label: '✨ Cave Treasure' },
      { type: 'trap', x: -9, z: 7, id: 'mt_goat', label: '🐐 Mountain Goat', threat: 'mountain_goat' },
      { type: 'mailbox', x: 10, z: 9, id: 'mt_lightning', label: '⚡ Lightning Strike', threat: 'lightning' },
      { type: 'lure', x: 6, z: 6, id: 'mountain_lure', label: '🍖 Food Scent' },
      { type: 'return_gate', x: 0, z: -8, id: 'mountain_exit', label: '🚪 Exit to Streets' },
    
      { type: 'treasure', x: 5, z: 5, id: 'mountain_mountain_rock', label: '✨ mountain_rock', item: 'mountain_rock' },
      { type: 'treasure', x: 5, z: 5, id: 'mountain_diamond_bone', label: '✨ diamond_bone', item: 'diamond_bone' },
      { type: 'treasure', x: 5, z: 5, id: 'mountain_magnet', label: '✨ magnet', item: 'magnet' },
      { type: 'treasure', x: 5, z: 5, id: 'mountain_cupcake', label: '✨ cupcake', item: 'cupcake' },],
    returnZone: 'suburban_streets',
    hint: 'The mountain air is crisp. Your human used to hike here with you.',
  },
  garden: {
    threat: 'garden_hose',
    threatKind: 'sneak',
    doorThreat: 'garden_snake',
    features: [
      { type: 'trap', x: -7, z: 9, id: 'garden_insect_feature', label: '🐛 Giant Insect', threat: 'garden_insect' },
    ],
    id: 'garden',
    transition: 'fade',
    name: '🌺 Secret Garden',
    desc: 'A hidden garden filled with beautiful flowers and peaceful paths.',
    type: 'fp',
    rooms: [
      { id: 'garden_entrance', name: 'Garden Gate', w: 120, h: 80, d: 150, color: '#FF69B4', exits: ['garden_main', 'garden_flowers'], isEntrance: true, entranceZone: 'suburban_streets' },
      { id: 'garden_main', name: 'Main Path', w: 200, h: 100, d: 180, color: '#FFB6C1', exits: ['garden_entrance', 'garden_fountain', 'garden_rose'], features: [{type:'fountain', x:100, y:50, w:60, h:40, label:'⛲ Fountain'}, { type: 'treasure', x: 50, y: 50, w: 40, h: 30, label: '✨ garden_flower', item: 'garden_flower' }, { type: 'treasure', x: 50, y: 50, w: 40, h: 30, label: '✨ food', item: 'food' }, { type: 'treasure', x: 50, y: 50, w: 40, h: 30, label: '✨ donut', item: 'donut' }, {type:'dog_friend', x:120, y:60, w:50, h:40, label:'🐕 Blossom in the Garden', companion:'garden_dog'}] },
      { id: 'garden_flowers', name: 'Flower Bed', w: 150, h: 90, d: 120, color: '#FFD700', exits: ['garden_main'], features: [{type:'hint', x:75, y:45, w:50, h:30, label:'🌸 Flowers', item:'flower'}] },
      { id: 'garden_fountain', name: 'Fountain Area', w: 160, h: 90, d: 140, color: '#87CEEB', exits: ['garden_main'], features: [{type:'water', x:80, y:45, w:40, h:30, label:'💧 Fountain'}] },
      { id: 'garden_rose', name: 'Rose Garden', w: 100, h: 80, d: 100, color: '#FF6347', exits: ['garden_main'], features: [{type:'secret_passage', x:50, y:40, w:40, h:30, label:'🔑 Rose Passage', item:'secret_key'}] }
    ],
    music: 'garden',
    hint: 'The roses smell like your human\'s garden. You remember playing here.',
    returnZone: 'suburban_streets',
  },
  library: {
    threat: 'library_silent',
    threatKind: 'comfort',
    doorThreat: 'library_boo',
    id: 'library',
    transition: 'wipe',
    name: '📚 Old Library',
    desc: 'A quiet library filled with books and mysterious secrets.',
    type: 'fp',
    rooms: [
      { id: 'library_entrance', name: 'Entrance Hall', w: 120, h: 80, d: 150, color: '#D2B48C', exits: ['library_main', 'library_stacks'], isEntrance: true, entranceZone: 'suburban_streets' },
      { id: 'library_main', name: 'Main Hall', w: 200, h: 100, d: 180, color: '#8B4513', exits: ['library_entrance', 'library_reference', 'library_special'], features: [{type:'person', x:100, y:50, w:40, h:60, label:'👤 Librarian Dog'}, { type: 'treasure', x: 50, y: 50, w: 40, h: 30, label: '✨ map_fragment', item: 'map_fragment' }, { type: 'treasure', x: 50, y: 50, w: 40, h: 30, label: '✨ photo', item: 'photo' }, {type:'dog_friend', x:120, y:60, w:50, h:40, label:'📖 Bookworm the Librarian', companion:'library_dog'}] },
      { id: 'library_stacks', name: 'Book Stacks', w: 150, h: 90, d: 120, color: '#654321', exits: ['library_main'], features: [{type:'hint', x:75, y:45, w:50, h:30, label:'📚 Books', item:'letter'}] },
      { id: 'library_reference', name: 'Reference Room', w: 160, h: 90, d: 140, color: '#8B6914', exits: ['library_main'], features: [{type:'hint', x:80, y:45, w:50, h:30, label:'🗺️ Maps', item:'treasure_map'}] },
      { id: 'library_special', name: 'Special Collection', w: 100, h: 80, d: 100, color: '#4a2a0a', exits: ['library_main'], features: [{type:'secret_passage', x:50, y:40, w:40, h:30, label:'🔑 Hidden Door', item:'secret_key'}] }
    ],
    music: 'library',
    hint: 'The books smell like home. Your human used to read to you here.',
    returnZone: 'suburban_streets',
  },
  market: {
    threat: 'market_fire',
    threatKind: 'timing',
    doorThreat: 'market_chase',
    id: 'market',
    transition: 'slide',
    name: '🏪 Town Market',
    desc: 'A bustling market with vendors selling treats, toys, and more.',
    type: 'fp',
    rooms: [
      { id: 'market_entrance', name: 'Market Gate', w: 120, h: 80, d: 150, color: '#FFD700', exits: ['market_main', 'market_food'], isEntrance: true, entranceZone: 'suburban_streets' },
      { id: 'market_main', name: 'Main Market', w: 200, h: 100, d: 180, color: '#FF69B4', exits: ['market_entrance', 'market_toys', 'market_treats'], features: [{type:'person', x:100, y:50, w:40, h:60, label:'👤 Market Vendor'}, { type: 'treasure', x: 50, y: 50, w: 40, h: 30, label: '✨ pizza_crust', item: 'pizza_crust' }, {type:'dog_friend', x:120, y:60, w:50, h:40, label:'🥖 Baker at the Market', companion:'market_dog'}] },
      { id: 'market_food', name: 'Food Stalls', w: 150, h: 90, d: 120, color: '#FFB6C1', exits: ['market_main'], features: [{type:'food', x:75, y:45, w:40, h:30, label:'🍖 Food', item:'pizza_crust'}] },
      { id: 'market_toys', name: 'Toy Shop', w: 160, h: 90, d: 140, color: '#87CEEB', exits: ['market_main'], features: [{type:'hint', x:80, y:45, w:50, h:30, label:'🧸 Toys', item:'dog_show_ribbon'}] },
      { id: 'market_treats', name: 'Treat Stand', w: 100, h: 80, d: 100, color: '#FFD700', exits: ['market_main'], features: [{type:'food', x:50, y:40, w:40, h:30, label:'🍪 Treats', item:'cookie'}] }
    ],
    music: 'market',
    hint: 'The smells of the market remind you of days spent shopping with your human.',
    returnZone: 'suburban_streets',
  },
  cave: {
    threat: 'raccoon',
    threatKind: 'combat',
    doorThreat: 'treasure_guardian',
    id: 'cave',
    transition: 'zoom',
    name: '🕳️ Crystal Cave',
    desc: 'A mysterious cave filled with glowing crystals and ancient secrets.',
    type: 'fp',
    rooms: [
      { id: 'cave_entrance', name: 'Cave Entrance', w: 120, h: 80, d: 150, color: '#2F4F4F', exits: ['cave_main', 'cave_deep'], isEntrance: true, entranceZone: 'forest' },
      { id: 'cave_main', name: 'Main Cave', w: 200, h: 100, d: 180, color: '#4682B4', exits: ['cave_entrance', 'cave_crystal', 'cave_deep'], features: [{type:'fountain', x:100, y:50, w:60, h:40, label:'💧 Crystal Spring'}] },
      { id: 'cave_crystal', name: 'Crystal Chamber', w: 150, h: 90, d: 120, color: '#87CEEB', exits: ['cave_main'], features: [{type:'treasure', x:75, y:45, w:50, h:30, label:'💎 Crystal Treasure', item:'cave_crystal'}] },
      { id: 'cave_deep', name: 'Deep Cave', w: 160, h: 90, d: 140, color: '#1a1a2e', exits: ['cave_main'], features: [{type:'secret_passage', x:80, y:45, w:50, h:30, label:'🔑 Secret Exit', item:'secret_key'}] }
    ],
    music: 'cave',
    hint: 'The crystals glow with a familiar light. You remember this place.',
    returnZone: 'suburban_streets',
  },
  waterfall: {
    threat: 'owl',
    threatKind: 'comfort',
    doorThreat: 'deer',
    id: 'waterfall',
    transition: 'fade',
    name: '💧 Waterfall Falls',
    desc: 'A majestic waterfall cascading into a peaceful pool below.',
    type: 'tp',
    music: 'waterfall',
    skyColor: '#87CEEB',
    groundColor: '#2d5a1e',
    dogColor: '#4a9eff',
    accentColor: '#006994',
    companions: ['lake_dog'],
    obstacles: [
      { type: 'tree', x: -6, z: 5, height: 4, trunkColor: '#5a3a1a', leafColor: '#2d5a1e' },
      { type: 'tree', x: 7, z: -4, height: 3.5, trunkColor: '#5a3a1a', leafColor: '#3a7a2e' },
      { type: 'bush', x: -8, z: -6, color: '#2d6a1e' },
      { type: 'bench', x: 4, z: 7, width: 2, color: '#8B6914' },
    ],
    npcs: [
      {
        id: 'waterfall_dog_npc',
        name: 'River',
        color: '#D2691E',
        accentColor: '#FFD700',
        x: 2,
        z: -3,
        dialogue: [
          'The waterfall is beautiful this time of year!',
          'There\'s a secret path behind the falls. Want to see?',
          'The pool below holds ancient treasures.',
          'Follow the water — it leads somewhere special.',
        ],
      },
    ],
    features: [
      { type: 'water', x: 0, z: 0, id: 'waterfall_pool', label: '💧 Waterfall Pool' },
      { type: 'scent_post', x: -7, z: 6, id: 'waterfall_scent', label: '🐾 Scent Post' },
      { type: 'treasure', x: 8, z: -7, id: 'waterfall_treasure', label: '✨ Hidden Treasure' },
      { type: 'lure', x: 5, z: 5, id: 'waterfall_lure', label: '🍖 Fish Scent' },
      { type: 'mailbox', x: -6, z: -4, id: 'wf_owl', label: '🦉 Night Owl', threat: 'owl' },
      { type: 'return_gate', x: 0, z: -8, id: 'waterfall_exit', label: '🚪 Exit to Streets' },
    ],
    returnZone: 'suburban_streets',
    hint: 'The sound of the waterfall is soothing. You remember playing here with your human.',
  },
  park_secret: {
    threat: 'treasure_guardian',
    threatKind: 'combat',
    doorThreat: 'park_tornado',
    id: 'park_secret',
    transition: 'zoom',
    name: '🌙 Secret Park',
    desc: 'A hidden park that only appears at night. Full of magical surprises.',
    type: 'tp',
    music: 'park_secret',
    skyColor: '#191970',
    groundColor: '#2d5a1e',
    dogColor: '#1a1a1a',
    accentColor: '#4a4a4a',
    companions: ['park_secret_dog'],
    obstacles: [
      { type: 'tree', x: -7, z: 5, height: 4, trunkColor: '#5a3a1a', leafColor: '#1a3a0a' },
      { type: 'tree', x: 8, z: -6, height: 3.5, trunkColor: '#5a3a1a', leafColor: '#2d5a1e' },
      { type: 'bush', x: -9, z: -7, color: '#2d6a1e' },
      { type: 'bench', x: 5, z: 7, width: 2, color: '#8B6914' },
    ],
    npcs: [
      {
        id: 'park_secret_dog_npc',
        name: 'Shadow',
        color: '#1a1a1a',
        accentColor: '#4a4a4a',
        x: -2,
        z: 4,
        dialogue: [
          'I know all the secret paths in the park.',
          'There\'s a hidden treasure behind the old oak tree.',
          'The moon bone only appears at night. Want to wait?',
          'Follow the shadows — they lead to the lake.',
        ],
      },
    ],
    features: [
      { type: 'fountain', x: 0, z: 0, id: 'secret_fountain', label: '🌙 Moon Fountain' },
      { type: 'scent_post', x: -8, z: 6, id: 'secret_scent', label: '🐾 Scent Post' },
      { type: 'treasure', x: 9, z: -8, id: 'secret_treasure', label: '✨ Moon Treasure' },
      { type: 'trap', x: -6, z: -6, id: 'secret_tornado', label: '🌪️ Park Tornado', threat: 'park_tornado' },
      { type: 'lure', x: 6, z: 6, id: 'secret_lure', label: '🍖 Moon Treat' },
      { type: 'return_gate', x: 0, z: -8, id: 'park_secret_exit', label: '🚪 Exit to Streets' },
    
      { type: 'treasure', x: 4, z: -3, id: 'park_secret_rainbow_bone', label: '✨ rainbow_bone', item: 'rainbow_bone' },],
    returnZone: 'suburban_streets',
    hint: 'The park glows under the moonlight. Your human used to bring you here at night.',
  }
}

export const ITEMS: Record<string, Item> = {
  bone: { name: '🦴 Bone', desc: 'A good bone. Smells familiar.', category: 'comfort' },
  treat: { name: '🍖 Treat', desc: 'Delicious! Restores happiness.', category: 'food' },
  toy: { name: '🧸 Toy', desc: 'A red ball. You remember this.', category: 'comfort' },
  key: { name: '🗝️ Key', desc: 'A small metal key.', category: 'key' },
  map_fragment: { name: '📋 Map Fragment', desc: 'Part of a map. Shows a street.', category: 'clue' },
  tree_clue: { name: '🌳 Tree Clue', desc: 'A tree you remember. Marked with a scratch.', category: 'clue' },
  friend: { name: '🐕 Friend', desc: 'A new companion!', category: 'comfort' },
  food: { name: '🍎 Food', desc: 'A snack for the road.', category: 'food' },
  collar_piece: { name: '📿 Collar Piece', desc: 'A piece of your collar. You recognize this.', category: 'key' },
  leash: { name: '🔗 Leash', desc: 'A red leash. Your human used this.', category: 'key' },
  collar: { name: '🎀 Collar', desc: 'Your collar! You remember wearing this.', category: 'key' },
  medal: { name: '🏅 Medal', desc: 'A dog show medal. You won this once.', category: 'comfort' },
  bone_necklace: { name: '🦴 Bone Necklace', desc: 'A necklace made of bones. Creepy but familiar.', category: 'comfort' },
  photo: { name: '📸 Photo', desc: 'A photo of you and your human. You miss them.', category: 'story' },
  blanket: { name: '🧶 Blanket', desc: 'A piece of your favorite blanket. Smells like home.', category: 'comfort' },
  water_bottle: { name: '💧 Water Bottle', desc: 'Half-full water. Perfect for a hot day.', category: 'comfort' },
  squirrel_dog: { name: '🐿️ Squirrel Toy', desc: 'A toy squirrel. You love this one.', category: 'comfort' },
  tennis_ball: { name: '🎾 Tennis Ball', desc: 'A slobbery tennis ball. Classic.', category: 'comfort' },
  dog_tag: { name: '🏷️ Dog Tag', desc: 'Your dog tag with your name on it.', category: 'key' },
  treat_bag: { name: '🥡 Treat Bag', desc: 'An open bag of treats. Jackpot!', category: 'food' },
  puzzle_piece: { name: '🧩 Puzzle Piece', desc: 'Part of a dog show puzzle. Shows a route.', category: 'crafting' },
  lake_stone: { name: '🪨 Lake Stone', desc: 'Smooth stone from the lake shore. Shiny.', category: 'crafting' },
  pet_shop_ticket: { name: '🎫 Pet Shop Ticket', desc: 'Admits you to the pet shop. Smells like treats.', category: 'crafting' },
  dog_show_ribbon: { name: '🎀 Dog Show Ribbon', desc: 'Blue ribbon from the dog show. You earned it!', category: 'crafting' },
  compass_fragment: { name: '🧭 Compass Fragment', desc: 'Half a compass. Points toward home.', category: 'crafting' },
  magic_bone: { name: '✨ Magic Bone', desc: 'Glows faintly. Smells like adventure.', category: 'crafting' },
  treasure_map: { name: '🗺️ Treasure Map', desc: 'Shows where secrets are hidden.', category: 'clue' },
  secret_key: { name: '🔑 Secret Key', desc: 'Opens hidden passages.', category: 'key' },
  golden_bone: { name: '🦴 Golden Bone', desc: 'The legendary golden bone. Pure magic.', category: 'rare' },
  warm_blanket: { name: '🧶 Warm Blanket', desc: 'Smells like your human. Comforting.', category: 'comfort' },
  favorite_toy: { name: '🧸 Favorite Toy', desc: 'Your old stuffed animal. Safe.', category: 'comfort' },
  comfort_bell: { name: '🔔 Comfort Bell', desc: 'Rings when near home.', category: 'comfort' },
  lake_crystal: { name: '💎 Lake Crystal', desc: 'Sparkles in the water. Magical.', category: 'rare' },
  pet_shop_treat: { name: '🍪 Pet Shop Treat', desc: 'Fresh from the bakery. Delicious!', category: 'food' },
  dog_show_trophy: { name: '🏆 Dog Show Trophy', desc: 'You won first place! Well done.', category: 'collectible' },
  shiny_rock: { name: '✨ Shiny Rock', desc: 'Glistens in the sun. Pretty.', category: 'collectible' },
  feather: { name: '🪶 Feather', desc: 'Soft and colorful. From a bird.', category: 'collectible' },
  pinecone: { name: '🌲 Pinecone', desc: 'From the forest. Smells like trees.', category: 'collectible' },
  flower: { name: '🌸 Flower', desc: 'Sweet smelling. Your human loved flowers.', category: 'collectible' },
  leaf: { name: '🍂 Leaf', desc: 'Autumn colored. Beautiful.', category: 'collectible' },
  shell: { name: '🐚 Shell', desc: 'From the lake shore. Smooth.', category: 'collectible' },
  home_photo: { name: '📸 Home Photo', desc: 'A photo of your home. You remember this place.', category: 'story' },
  collar_buckle: { name: '🔗 Collar Buckle', desc: 'Part of your collar. You recognize it.', category: 'key' },
  dog_license: { name: '📋 Dog License', desc: 'Your official dog license. Real proof of home.', category: 'key' },
  rainbow_bone: { name: '🌈 Rainbow Bone', desc: 'Shimmers with all colors. Legendary!', category: 'rare' },
  moon_bone: { name: '🌙 Moon Bone', desc: 'Glows in the dark. Magical.', category: 'rare' },
  star_bone: { name: '⭐ Star Bone', desc: 'Sparkles like a star. Rare!', category: 'rare' },
  pizza_crust: { name: '🍕 Pizza Crust', desc: 'Found on the sidewalk. Smells good.', category: 'food' },
  hot_dog: { name: '🌭 Hot Dog', desc: 'A real hot dog! Wait... is that...?', category: 'food' },
  ice_cream: { name: '🍦 Ice Cream', desc: 'Still frozen! Sweet and cold.', category: 'food' },
  cookie: { name: '🍪 Cookie', desc: 'Chocolate chip. Perfect.', category: 'food' },
  cupcake: { name: '🧁 Cupcake', desc: 'With sprinkles. Festive!', category: 'food' },
  donut: { name: '🍩 Donut', desc: 'Glazed. Simple perfection.', category: 'food' },
  flashlight: { name: '🔦 Flashlight', desc: 'Lights up dark places. Useful.', category: 'utility' },
  rope: { name: '🪢 Rope', desc: 'Tough and long. Can tie things.', category: 'utility' },
  magnet: { name: '🧲 Magnet', desc: 'Attracts metal. Weirdly useful.', category: 'utility' },
  umbrella: { name: '☂️ Umbrella', desc: 'Keeps you dry in rain. Comforting.', category: 'utility' },
  letter: { name: '✉️ Letter', desc: 'A letter addressed to you. From your human?', category: 'story' },
  diary_page: { name: '📄 Diary Page', desc: 'Your human wrote about you here. Sweet.', category: 'story' },
  forest_mushroom: { name: '🍄 Forest Mushroom', desc: 'Colorful and strange. Don\'t eat it.', category: 'collectible' },
  cave_crystal: { name: '💎 Cave Crystal', desc: 'Glowing from within. Magical.', category: 'rare' },
  beach_shell: { name: '🐚 Beach Shell', desc: 'From the shore. Smooth and pretty.', category: 'collectible' },
  mountain_rock: { name: '🪨 Mountain Rock', desc: 'Heavy and ancient. Powerful.', category: 'collectible' },
  garden_flower: { name: '🌺 Garden Flower', desc: 'Bright and beautiful. Your human grew these.', category: 'collectible' },
  golden_treat: { name: '🍖 Golden Treat', desc: 'Shines like gold. Legendary snack!', category: 'collectible' },
  diamond_bone: { name: '💎 Diamond Bone', desc: 'Sparkles with diamonds. Incredible!', category: 'collectible' },
  rainbow_ribbon: { name: '🌈 Rainbow Ribbon', desc: 'Colors shift and change. Magical.', category: 'collectible' },
  companion_treat: { name: '🍖 Companion Treat', desc: 'Special treat for friends. They love it.', category: 'collectible' },
  companion_toy: { name: '🧸 Companion Toy', desc: 'A toy your friends would enjoy.', category: 'collectible' },
}

export const THREATS: Record<string, Threat> = {
  traffic: {
    name: 'Traffic',
    icon: '🚗',
    type: 'timing',
    description: 'Cars are zooming by! Time your crossing!',
    solve: 'Press SPACE when the gap is right',
    mangaText: 'SCREEEECH!',
    mangaType: 'near-miss',
    scene: 'street',
    successLine: 'You slip through the gap just as the brakes screech.',
    failLine: 'The car swerves around you — you bolt into the bushes, heart pounding.',
    difficulty: { gapWidth: 22, speed: 48 }
  },
  cat: {
    name: 'Mean Cat',
    icon: '🐱',
    type: 'combat',
    description: 'A hissing cat blocks the path!',
    solve: 'Press SPACE in rhythm to scare it off',
    mangaText: 'SCRATCH!',
    mangaType: 'fight',
    scene: 'street',
    beats: ['HISS!', 'SCREECH!', 'SCATTER!'],
    successLine: 'The cat bolts up a fence, tail puffed to twice its size.',
    failLine: 'It rakes your ear. You slink away with a sting and a grudge.'
  },
  bully: {
    name: 'Bully Dog',
    icon: '🐕‍🦺',
    type: 'combat',
    description: 'A tough-looking dog growls at you!',
    solve: 'Press SPACE in rhythm to intimidate it',
    mangaText: 'GRRR!',
    mangaType: 'fight',
    scene: 'street',
    beats: ['GROWL!', 'SNAP!', 'BACK OFF!'],
    successLine: 'The bully breaks eye contact first and pads off, tail low.',
    failLine: 'You back away slowly — smart. That\'s how you survive.',
    difficulty: { pulseSpeed: 0.8 }
  },
  storm: {
    name: 'Thunderstorm',
    icon: '⛈️',
    type: 'comfort',
    description: 'Thunder roars! Find shelter or comfort yourself.',
    solve: 'Find shelter quickly or use a comfort item',
    mangaText: 'BOOM!',
    mangaType: 'scare',
    scene: 'apartment',
    successLine: 'Thunder rumbles overhead, muffled by the ceiling. Almost cozy.',
    failLine: 'Lightning pops right outside the window. You shake, ears flat.'
  },
  vacuum: {
    name: 'Vacuum Monster',
    icon: '🤖',
    type: 'sneak',
    description: 'The dreaded vacuum cleaner! Hide!',
    solve: 'Stay still when it approaches, move when safe',
    mangaText: 'VRRRRR!',
    mangaType: 'scare',
    scene: 'shelter',
    successLine: 'The vacuum roars past — you were a statue. It loses interest.',
    failLine: 'It corners you! You scramble up the shelving, ears ringing.',
    difficulty: { riseRate: 35 }
  },
  mailman: {
    name: 'Mail Carrier',
    icon: '📬',
    type: 'timing',
    description: 'The mail carrier is coming! They might have something for you.',
    solve: 'Press SPACE to intercept the mail package',
    mangaText: 'THUMP!',
    mangaType: 'near-miss',
    scene: 'street',
    successLine: 'You intercept the package before it hits the porch. The scent says: home.',
    failLine: 'The carrier scoops it up and walks on. The scent fades.',
    difficulty: { gapWidth: 26, speed: 42 }
  },
  garden_hose: {
    name: 'Garden Hose',
    icon: '🚿',
    type: 'sneak',
    description: 'A sprinkler is spraying everywhere! Stay dry!',
    solve: 'Move to the dry zone when the sprinkler is away',
    mangaText: 'SPRINKLE!',
    mangaType: 'scare',
    scene: 'garden',
    successLine: 'The sprinkler swings past. You stay dry — and proud.',
    failLine: 'Soggy. Soaking. You drip behind the rose bush.',
    difficulty: { riseRate: 28, fallRate: 22 }
  },
  construction: {
    name: 'Construction Crew',
    icon: '🚧',
    type: 'timing',
    description: 'Heavy machinery is working! Watch for the crane!',
    solve: 'Press SPACE when the crane arm is clear',
    mangaText: 'CLANG!',
    mangaType: 'near-miss',
    scene: 'street',
    successLine: 'The crane arm swings wide. You\'re already in its shadow.',
    failLine: 'Dirt thuds down where you stood. You scatter, nose low.',
    difficulty: { gapWidth: 20, speed: 52 }
  },
  ice_cream_truck: {
    name: 'Ice Cream Truck',
    icon: '🍦',
    type: 'comfort',
    description: 'The ice cream truck is here! But can you reach it?',
    solve: 'Follow the music and catch the truck before it leaves',
    mangaText: 'DOOOOONG!',
    mangaType: 'scare',
    scene: 'park',
    successLine: 'You catch the truck mid-song. The window smells like vanilla.',
    failLine: 'It rounds the corner and goes. You chase the jingle three blocks.',
    difficulty: { holdRate: 22, timeLimit: 7 }
  },
  squirrel: {
    name: 'Squirrel',
    icon: '🐿️',
    type: 'sneak',
    description: 'A squirrel is taunting you from a tree!',
    solve: 'Stay still and wait for the right moment to pounce',
    mangaText: 'SQUEAK!',
    mangaType: 'near-miss',
    scene: 'forest',
    successLine: 'It freezes, eyes wide. Then it\'s gone up a pine, safe.',
    failLine: 'It darts to a higher branch, chittering at you. Rude.',
    difficulty: { riseRate: 25, fallRate: 25 }
  },
  neighbor_dog: {
    name: 'Neighbor Dog',
    icon: '🐕',
    type: 'combat',
    description: 'A friendly dog wants to play! But how to respond?',
    solve: 'Press SPACE to bark back or wag tail',
    mangaText: 'WOOF!',
    mangaType: 'fight',
    scene: 'street',
    beats: ['WOOF!', 'WOOF-WOOF!'],
    successLine: 'You bark back. It wags. A new friend for the road?',
    failLine: 'It takes your silence as a dare and charges. You zig-zag away.',
    difficulty: { beats: 2, pulseSpeed: 0.6, targetWindow: 0.26 }
  },
  storm_sewer: {
    name: 'Storm Drain',
    icon: '🕳️',
    type: 'timing',
    description: 'Rain is filling the storm drain! Your toy might be down there!',
    solve: 'Press SPACE to grab the toy before it washes away',
    mangaText: 'WHOOSH!',
    mangaType: 'scare',
    scene: 'park',
    successLine: 'You grab the toy mid-swirl. The drain spits it out to you.',
    failLine: 'The current wins. It swirls down, gone to the river.',
    difficulty: { gapWidth: 20, speed: 55 }
  },
  // New threats from new zones
  lake_ripple: {
    name: 'Lake Ripple',
    icon: '🌊',
    type: 'timing',
    description: 'Ripples in the lake! Something is coming!',
    solve: 'Press SPACE to jump over the wave',
    mangaText: 'SPLASH!',
    mangaType: 'scare',
    scene: 'lake',
    successLine: 'You leap the ripple. Water clings to your paws, then flies off.',
    failLine: 'The ripple catches your haunches. You shake off a lake\'s worth.',
    difficulty: { gapWidth: 22, speed: 48 }
  },
  pet_shop_cat: {
    name: 'Pet Shop Cat',
    icon: '🐱',
    type: 'combat',
    description: 'A pampered cat guards the treats!',
    solve: 'Press SPACE in rhythm to distract it',
    mangaText: 'MEOW!',
    mangaType: 'fight',
    scene: 'pet_shop',
    beats: ['MEOW!', 'HUFF!', 'CLINK!'],
    successLine: 'The cat swats a shelf, scolds the room, and regales itself.',
    failLine: 'It drops a fish bowl. The clerk gasps. You feel small.'
  },
  dog_show_judge: {
    name: 'Dog Show Judge',
    icon: '👔',
    type: 'timing',
    description: 'The judge is watching! Pose correctly!',
    solve: 'Press SPACE when the pose indicator aligns',
    mangaText: 'POSE!',
    mangaType: 'near-miss',
    scene: 'dog_show',
    successLine: 'Perfect pose. The judge\'s pencil pauses — a real compliment.',
    failLine: 'You break form. The crowd murmurs. One less ribbon for you.',
    difficulty: { gapWidth: 18, speed: 50 }
  },
  forest_wolf: {
    name: 'Forest Wolf',
    icon: '🐺',
    type: 'combat',
    description: 'A wild wolf blocks the path!',
    solve: 'Press SPACE in rhythm to assert dominance',
    mangaText: 'HOWL!',
    mangaType: 'fight',
    scene: 'forest',
    beats: ['SNARL!', 'HOWL!', 'YIELD!'],
    successLine: 'It holds your gaze, then drops its head and slips into the pines.',
    failLine: 'Its shadow falls over you. You back away one slow step at a time.',
    difficulty: { pulseSpeed: 0.8, targetWindow: 0.18 }
  },
  beach_crab: {
    name: 'Beach Crab',
    icon: '🦀',
    type: 'sneak',
    description: 'A crab with giant claws! Hide!',
    solve: 'Stay still when the crab approaches, move when safe',
    mangaText: 'CLICK!',
    mangaType: 'scare',
    scene: 'beach',
    successLine: 'It pinches the sand, not you. You back off, shell to shell.',
    failLine: 'A claw snaps your ear. You hop around the dune in a circle.',
    difficulty: { riseRate: 30, fallRate: 18 }
  },
  mountain_goat: {
    name: 'Mountain Goat',
    icon: '🐐',
    type: 'timing',
    description: 'A goat charges down the mountain!',
    solve: 'Press SPACE to dodge at the right moment',
    mangaText: 'CLACK!',
    mangaType: 'near-miss',
    scene: 'mountain',
    successLine: 'It rounds the boulder at full gallop. You\'re already under the ledge.',
    failLine: 'Hooves thunder past. You dive into the scree — and slide with it.',
    difficulty: { gapWidth: 18, speed: 58 }
  },
  garden_snake: {
    name: 'Garden Snake',
    icon: '🐍',
    type: 'sneak',
    description: 'A snake slithers through the flowers!',
    solve: 'Move away slowly without sudden movements',
    mangaText: 'HISS!',
    mangaType: 'scare',
    scene: 'garden',
    successLine: 'It unhooks from the rose and vanishes into the fence. No scales lost.',
    failLine: 'It strikes at your tail. You yelp and scramble over the hedge.',
    difficulty: { riseRate: 24, fallRate: 24 }
  },
  library_silent: {
    name: 'Library Silence',
    icon: '🤫',
    type: 'comfort',
    description: 'The librarian shushes you! Find quiet comfort.',
    solve: 'Find a cozy spot and stay quiet',
    mangaText: 'SHHH!',
    mangaType: 'scare',
    scene: 'library',
    successLine: 'You settle under the reading nook. Even the dust motes hush.',
    failLine: 'The librarian\'s finger points. You tiptoe out, tail between.',
    difficulty: { holdRate: 20, timeLimit: 8 }
  },
  market_chase: {
    name: 'Market Chase',
    icon: '🏃',
    type: 'timing',
    description: 'Vendors are rushing! Dodge the crowd!',
    solve: 'Press SPACE to weave through the crowd',
    mangaText: 'MOVE!',
    mangaType: 'near-miss',
    scene: 'market',
    successLine: 'You weave through the gap between cabbages and fish. Clean.',
    failLine: 'A fish basket clips your back. You scatter, scales everywhere.',
    difficulty: { gapWidth: 20, speed: 54 }
  },
  park_squirrel: {
    name: 'Park Squirrel Army',
    icon: '🐿️',
    type: 'combat',
    description: 'A horde of squirrels attacks!',
    solve: 'Press SPACE in rhythm to scare them off',
    mangaText: 'SQUEAK!',
    mangaType: 'fight',
    scene: 'park',
    beats: ['SQUEAK!', 'SQUIRM!', 'SCATTER!'],
    successLine: 'The army scatters up the oak in a brown storm. Acorns rain.',
    failLine: 'They mob your tail. You bark, they shriek, the park is chaos.',
    difficulty: { pulseSpeed: 0.75 }
  },
  // New environmental threats
  fog: {
    name: 'Thick Fog',
    icon: '🌫️',
    type: 'comfort',
    description: 'Visibility is zero! Find your way through.',
    solve: 'Follow the scent trail through the fog',
    mangaText: 'FOG!',
    mangaType: 'scare',
    scene: 'lake',
    successLine: 'You follow the scent until the fog thins into morning light.',
    failLine: 'You circle the same birch three times. The fog wins a round.',
    difficulty: { holdRate: 22, timeLimit: 8 }
  },
  lightning: {
    name: 'Lightning Strike',
    icon: '⚡',
    type: 'timing',
    description: 'Lightning flashes! Find shelter quickly!',
    solve: 'Press SPACE to run to the nearest shelter',
    mangaText: 'ZAP!',
    mangaType: 'scare',
    scene: 'mountain',
    successLine: 'You reach the cave mouth as the bolt takes the peak.',
    failLine: 'The flash catches you open on the scree. You shake for a minute.',
    difficulty: { gapWidth: 16, speed: 60 }
  },
  flood: {
    name: 'Flash Flood',
    icon: '🌊',
    type: 'sneak',
    description: 'Water is rising! Find high ground!',
    solve: 'Move to elevated areas before the water reaches you',
    mangaText: 'WHOOSH!',
    mangaType: 'scare',
    scene: 'lake',
    successLine: 'You reach the ledge just as the water surges. Dry and safe.',
    failLine: 'The flood catches your paws. You swim — and it\'s colder than it looks.',
    difficulty: { riseRate: 40, fallRate: 15, safeHold: 4 }
  },
  earthquake: {
    name: 'Earthquake',
    icon: '🌍',
    type: 'timing',
    description: 'The ground is shaking! Stay balanced!',
    solve: 'Press SPACE to stabilize yourself',
    mangaText: 'RUMBLE!',
    mangaType: 'scare',
    scene: 'street',
    successLine: 'You find your balance as the windows rattle. You didn\'t flinch.',
    failLine: 'The floor lurches. You crash into a doorframe — a very rude doorframe.',
    difficulty: { gapWidth: 18, speed: 56 }
  },
  // New animal threats
  raccoon: {
    name: 'Raccoon Bandit',
    icon: '🦝',
    type: 'combat',
    description: 'A raccoon steals your items!',
    solve: 'Press SPACE in rhythm to retrieve your things',
    mangaText: 'GRAB!',
    mangaType: 'fight',
    scene: 'cave',
    beats: ['GRAZE!', 'GRAB!', 'GONE!'],
    successLine: 'You pounce. The raccoon drops the scrap and vanishes into the dark.',
    failLine: 'It vanishes with your snack. You hear it munching, smug.',
    difficulty: { pulseSpeed: 0.75 }
  },
  owl: {
    name: 'Night Owl',
    icon: '🦉',
    type: 'comfort',
    description: 'A large owl stares at you in the dark!',
    solve: 'Stay calm and blink slowly to show friendliness',
    mangaText: 'HOOT!',
    mangaType: 'scare',
    scene: 'waterfall',
    successLine: 'It blinks, slow as a waterfall. You blink back. An understanding is reached.',
    failLine: 'You startle. It hoots — and the whole ravine answers.',
    difficulty: { holdRate: 18, timeLimit: 9 }
  },
  deer: {
    name: 'Deer Herd',
    icon: '🦌',
    type: 'sneak',
    description: 'A herd of deer blocks the path!',
    solve: 'Wait patiently for them to move aside',
    mangaText: 'PRANCE!',
    mangaType: 'near-miss',
    scene: 'waterfall',
    successLine: 'They part around you like a river around a stone. Silent.',
    failLine: 'You spook the herd. They stampede, and the moss shakes.',
    difficulty: { riseRate: 22, fallRate: 26 }
  },
  // New special threats
  treasure_guardian: {
    name: 'Treasure Guardian',
    icon: '🗡️',
    type: 'combat',
    description: 'A legendary guardian protects the treasure!',
    solve: 'Press SPACE in rhythm to prove your worthiness',
    mangaText: 'CLANG!',
    mangaType: 'fight',
    scene: 'cave',
    beats: ['CLANG!', 'FLASH!', 'WORTHY!', 'OPEN!'],
    successLine: 'The guardian steps aside. The treasure glints, patient and old.',
    failLine: 'Its blade rings the stone. You live to try again — probably.',
    difficulty: { beats: 4, pulseSpeed: 0.8, targetWindow: 0.16 }
  },
  // New zone-specific threats
  lake_monster: {
    name: 'Lake Monster',
    icon: '🐉',
    type: 'combat',
    description: 'Something large stirs beneath the lake!',
    solve: 'Press SPACE in rhythm to calm the waters',
    mangaText: 'SPLASH!',
    mangaType: 'fight',
    scene: 'lake',
    beats: ['SPLASH!', 'SURGE!', 'STILL!'],
    successLine: 'The water calms. Something huge exhales beneath you — and passes.',
    failLine: 'A fin the size of a fence slams the lake. You swim. You swim hard.',
    difficulty: { pulseSpeed: 0.8 }
  },
  pet_shop_bell: {
    name: 'Pet Shop Bell',
    icon: '🔔',
    type: 'timing',
    description: 'The door bell won\'t stop ringing!',
    solve: 'Press SPACE to silence it before the cat notices',
    mangaText: 'DING!',
    mangaType: 'near-miss',
    scene: 'pet_shop',
    successLine: 'You ring it once, cleanly. The shop exhales. Peace.',
    failLine: 'It rings and rings. The cat\'s ears swivel like satellites.',
    difficulty: { gapWidth: 24, speed: 44 }
  },
  dog_show_roar: {
    name: 'Dog Show Roar',
    icon: '🦁',
    type: 'combat',
    description: 'The crowd roars! Stand your ground!',
    solve: 'Press SPACE in rhythm to show confidence',
    mangaText: 'ROAR!',
    mangaType: 'fight',
    scene: 'dog_show',
    beats: ['WOOF!', 'POSE!', 'BOW!'],
    successLine: 'The crowd roars. You hold your pose — and it\'s for you.',
    failLine: 'The noise swells. You blink. One ribbon slips off your chest.'
  },
  forest_thorn: {
    name: 'Forest Thorns',
    icon: '🌿',
    type: 'sneak',
    description: 'Thorny vines block the path!',
    solve: 'Find the safe passage through the thorns',
    mangaText: 'PRICK!',
    mangaType: 'scare',
    scene: 'forest',
    successLine: 'You find the gap in the brambles and slip through uncut.',
    failLine: 'A thorn hooks your collar. You twist free, brambles in your fur.',
    difficulty: { riseRate: 26, fallRate: 22 }
  },
  beach_wave: {
    name: 'Big Wave',
    icon: '🌊',
    type: 'timing',
    description: 'A huge wave approaches the shore!',
    solve: 'Press SPACE to jump to safety',
    mangaText: 'CRASH!',
    mangaType: 'scare',
    scene: 'beach',
    successLine: 'You spring to the dune as the wave crashes. Sand, not seawater.',
    failLine: 'The wave takes your legs. You\'re a sock in a washing machine.',
    difficulty: { gapWidth: 20, speed: 55 }
  },
  mountain_rockfall: {
    name: 'Rockfall',
    icon: '🪨',
    type: 'timing',
    description: 'Rocks are falling from above!',
    solve: 'Press SPACE to dodge the falling rocks',
    mangaText: 'CLATTER!',
    mangaType: 'scare',
    scene: 'mountain',
    successLine: 'You roll under the boulder\'s shadow. Dust settles. You\'re still here.',
    failLine: 'A stone clips your shoulder. You scramble up the slope, ears ringing.',
    difficulty: { gapWidth: 17, speed: 57 }
  },
  garden_insect: {
    name: 'Giant Insect',
    icon: '🐛',
    type: 'sneak',
    description: 'A giant bug crawls toward you!',
    solve: 'Stay still and hope it moves on',
    mangaText: 'BUZZ!',
    mangaType: 'scare',
    scene: 'garden',
    successLine: 'It pauses, antennae twitching, and crawls on without you.',
    failLine: 'It lands on your nose. You sneeze. It sneezes back. You bolt.',
    difficulty: { riseRate: 20, fallRate: 28 }
  },
  library_boo: {
    name: 'Library Boo',
    icon: '👻',
    type: 'comfort',
    description: 'A ghostly figure appears among the books!',
    solve: 'Show kindness to the spirit',
    mangaText: 'BOO!',
    mangaType: 'scare',
    scene: 'library',
    successLine: 'You show your paws are empty. The spirit nods and shelves a book.',
    failLine: 'The shelves creak. Something cold follows you to the door.',
    difficulty: { holdRate: 20, timeLimit: 8 }
  },
  market_fire: {
    name: 'Market Fire',
    icon: '🔥',
    type: 'timing',
    description: 'A stall catches fire! Help put it out!',
    solve: 'Press SPACE to grab water buckets',
    mangaText: 'WHOOSH!',
    mangaType: 'scare',
    scene: 'market',
    successLine: 'You grab the bucket and toss it. The stall\'s saved. The vendor hugs your head.',
    failLine: 'The flames leap the crate. You back off, whiskers singed.',
    difficulty: { gapWidth: 19, speed: 52 }
  },
  park_tornado: {
    name: 'Park Tornado',
    icon: '🌪️',
    type: 'sneak',
    description: 'A small tornado forms in the park!',
    solve: 'Find the safest shelter quickly',
    mangaText: 'WHOOSH!',
    mangaType: 'scare',
    scene: 'secret_park',
    successLine: 'You duck under the old oak. The wind howls over your head.',
    failLine: 'The funnels lift your tail. You fight your way to the stone wall.',
    difficulty: { riseRate: 32, fallRate: 18 }
  }
}

// Export all data as a single object for bootstrapping
export const GAME_DATA = { DOGS, ZONES, ITEMS, THREATS, COMPANIONS };
