/**
 * Game content data — DOGS, ZONES, ITEMS, THREATS, COMPANIONS
 *
 * v2.1 — Full port of the v1 world (19 zones, 15 companions, 69 items, 45 threats)
 * into v2's strict types. Merged from v2 dog data + turbo-game-v1-archive content.
 * Safe to edit by hand afterwards.
 */

import type { Dog, Zone, Item, Threat, Companion } from './types';

export const DOGS: Record<string, Dog> = {
  turbo: {
    id: 'turbo',
    name: 'Turbo',
    breed: 'Alaskan Husky',
    trait: 'speed' as const,
    traitDesc: 'Moves faster, escapes threats quicker',
    colors: { fur: ['#ffffff', '#3a3a3a', '#8B4513'], accent: '#4a9eff' },
    personality: ['adventurous', 'loyal', 'curious'] as const,
    lines: {
      intro: "The gate was open. I don't remember opening it... but the world is OUTSIDE.",
      happy: "Woof! Best day ever!",
      scared: "What was that?! ...I'm not scared. I'm just cautiously observant.",
      hint: "I smell something familiar... like home?",
      combat: "Leave it to me! *growls bravely*",
      foundFriend: "A new friend?! *wags tail furiously*"
    }
  },
  watson: {
    id: 'watson',
    name: 'Watson',
    breed: 'German Shepherd',
    trait: 'brave' as const,
    traitDesc: 'Combat is easier, intimidation works',
    colors: { fur: ['#2a1a0a', '#4a2a0a', '#1a0a00'], accent: '#d4a020' },
    personality: ['brave', 'protective', 'disciplined'] as const,
    lines: {
      intro: "I don't know where I am, but if anything threatens anyone, it'll answer to me.",
      happy: "*stays alert but tail gives a small wag*",
      scared: "*ears flatten, then stands taller* I'm fine. Really.",
      hint: "That direction... I should investigate.",
      combat: "Not on my watch. *steps forward*",
      foundFriend: "A fellow warrior? ...Do you know the way home?"
    }
  },
  nova: {
    id: 'nova',
    name: 'Nova',
    breed: 'Golden Retriever',
    trait: 'happiness' as const,
    traitDesc: 'Companions boost more, morale decays slower',
    colors: { fur: ['#DAA520', '#FFD700', '#B8860B'], accent: '#ff9f43' },
    personality: ['friendly', 'optimistic', 'generous'] as const,
    lines: {
      intro: "Oh wow! Everything is so big and new! I hope I make lots of friends!",
      happy: "This is the BEST thing that's ever happened! *does happy pirouette*",
      scared: "*whimpers* ...But I'll be brave for everyone!",
      hint: "Ooh! A clue! Maybe we're getting closer to home!",
      combat: "*barks confidently* They won't hurt my friends!",
      foundFriend: "A new friend?! *immediately starts playing*"
    }
  },
  walter: {
    id: 'walter',
    name: 'Walter',
    breed: 'English Bulldog',
    trait: 'sniff' as const,
    traitDesc: 'Finds food and hints faster',
    colors: { fur: ['#D2B48C', '#C4A882', '#8B7355'], accent: '#e07040' },
    personality: ['food-motivated', 'calm', 'stubborn'] as const,
    lines: {
      intro: "I was napping... now I'm somewhere else. Hope there's food here.",
      happy: "*pants happily* Nothing beats a good day and a good snack.",
      scared: "*huffs* I'm not afraid of... *hears noise* ...of anything.",
      hint: "*sniff sniff* ...Yeah, that smells like home. Definitely home.",
      combat: "*stands his ground, looking like he's about to sneeze*",
      foundFriend: "*sniffs new dog* ...Do you have snacks? ...Wait, you're a friend?"
    }
  },
  beaux: {
    id: 'beaux',
    name: 'Beaux',
    breed: 'Chihuahua',
    trait: 'compact' as const,
    traitDesc: 'Carries extra item in tiny bandana',
    colors: { fur: ['#F5DEB3', '#DEB887', '#D2B48C'], accent: '#ff6b81' },
    personality: ['tough', 'tiny', 'surprisingly brave'] as const,
    lines: {
      intro: "I may be small, but I'm NOT insignificant. And I have a bandana. Look.",
      happy: "*tiny happy yips* I am the best dog. Everyone knows this.",
      scared: "*makes himself look bigger* I'm not scared! I'm just... very alert!",
      hint: "*ears perk up* I can smell it from here. Well, maybe two blocks away.",
      combat: "*barks at volume 11* Who's the boss now?! *is 8 inches tall*",
      foundFriend: "*sniffs* You're big. I'm... I'm not intimidated at all. *is very intimidated*"
    }
  }
}

export const COMPANIONS: Record<string, Companion> = {
  stray_buddy: {
    id: 'stray_buddy',
    name: 'Buddy',
    breed: 'Golden Retriever',
    trait: '🐾 Friendly',
    dialogue: [
      'Woof! Welcome to the park!',
      'Home is where the fence is. Which fence?',
      'I used to live near the big oak tree!',
      'Follow the scent posts — they lead somewhere!',
    ],
    color: '#DAA520',
    accentColor: '#FFD700',
    met: false,
    active: false,
  },
  shelter_dog: {
    id: 'shelter_dog',
    name: 'Rex',
    breed: 'Mixed Breed',
    trait: '🗺️ Navigator',
    dialogue: [
      'I was here a long time ago. I remember the way out.',
      'The kennels... they\'re not so bad if you find a friend.',
      'There\'s a side gate. The guard leaves it unlatched sometimes.',
      'Follow the scent posts — they lead somewhere!',
    ],
    color: '#5a4a3a',
    accentColor: '#8a7a5a',
    met: false,
    active: false,
  },
  park_stray: {
    id: 'park_stray',
    name: 'Luna',
    breed: 'Border Collie',
    trait: '🧠 Smart',
    dialogue: [
      'I can help you find your way. I\'ve been watching things.',
      'The apartment building has a back entrance. Watch for the cat.',
      'I\'ve seen dogs go that way. They came back... mostly okay.',
      'The neighborhood is close. I can feel it in my paws.',
    ],
    color: '#3a3a3a',
    accentColor: '#ffffff',
    met: false,
    active: false,
  },
  neighborhood_dog: {
    id: 'neighborhood_dog',
    name: 'Max',
    breed: 'Labrador Retriever',
    trait: '🦴 Finder',
    dialogue: [
      'I live nearby! Well, I lived nearby. Now I visit.',
      'This is my old neighborhood. I know every squirrel.',
      'The house with the golden gate? That\'s the one!',
      'My human used to bring me here. It was the best.',
    ],
    color: '#B8860B',
    accentColor: '#DAA520',
    met: false,
    active: false,
  },
  alley_cat_friendly: {
    id: 'alley_cat_friendly',
    name: 'Whiskers',
    breed: 'Cat',
    trait: '👁️ Watcher',
    dialogue: [
      'Dogs. Always dogs. But... you seem nice.',
      'I\'ve seen things from the rooftops. Things you couldn\'t imagine.',
      'The shelter has a back exit. But the cat guard is fierce.',
      'If you want to find home, follow the smells. Cats don\'t forget.',
    ],
    color: '#6a6a6a',
    accentColor: '#9a9a9a',
    met: false,
    active: false,
  },
  // New companions from new zones
  lake_dog: {
    id: 'lake_dog',
    name: 'River',
    breed: 'Nova Scotia Duck Tolling Retriever',
    trait: '🏊 Swimmer',
    dialogue: [
      'The lake is beautiful this time of year!',
      'I used to swim here every day with my human.',
      'There\'s a secret path behind the waterfall. Want to see?',
      'Follow the water — it leads somewhere special.',
    ],
    color: '#D2691E',
    accentColor: '#FFD700',
    met: false,
    active: false,
  },
  pet_shop_dog: {
    id: 'pet_shop_dog',
    name: 'Coco',
    breed: 'Poodle',
    trait: '✨ Groomed',
    dialogue: [
      'Oh my! You\'re so scruffy! Let me help!',
      'I know all the best treats in town!',
      'The dog show is coming up! Want to enter?',
      'My human takes me to the pet shop every week!',
    ],
    color: '#FFB6C1',
    accentColor: '#FF69B4',
    met: false,
    active: false,
  },
  dog_show_dog: {
    id: 'dog_show_dog',
    name: 'Champion',
    breed: 'Standard Poodle',
    trait: '🏆 Champion',
    dialogue: [
      'I\'ve won every dog show in the region!',
      'Would you like to compete? I can train you!',
      'The secret to winning is confidence and treats!',
      'Follow the crowd — they all head to the park!',
    ],
    color: '#FFFFFF',
    accentColor: '#FFD700',
    met: false,
    active: false,
  },
  forest_dog: {
    id: 'forest_dog',
    name: 'Forest',
    breed: 'German Shorthaired Pointer',
    trait: '🌲 Hunter',
    dialogue: [
      'The forest is vast and full of wonders!',
      'I can smell home from here! Well, almost.',
      'Watch out for the storm drain ahead!',
      'The cave behind the waterfall holds secrets.',
    ],
    color: '#8B4513',
    accentColor: '#D2691E',
    met: false,
    active: false,
  },
  beach_dog: {
    id: 'beach_dog',
    name: 'Surfer',
    breed: 'Australian Shepherd',
    trait: '🏄 Surfer',
    dialogue: [
      'The beach is my happy place!',
      'I found a treasure map here once! Want to see?',
      'The waves bring all sorts of interesting things.',
      'Follow the seagulls — they know where the good stuff is!',
    ],
    color: '#4682B4',
    accentColor: '#87CEEB',
    met: false,
    active: false,
  },
  mountain_dog: {
    id: 'mountain_dog',
    name: 'Peak',
    breed: 'Bernese Mountain Dog',
    trait: '⛰️ Climber',
    dialogue: [
      'The mountain path is steep but worth it!',
      'I\'ve seen dogs go up there and come back with stories.',
      'The cave at the top holds ancient treasures.',
      'Watch your step on the rocky paths!',
    ],
    color: '#2F4F4F',
    accentColor: '#708090',
    met: false,
    active: false,
  },
  garden_dog: {
    id: 'garden_dog',
    name: 'Blossom',
    breed: 'Cavalier King Charles Spaniel',
    trait: '🌸 Gentle',
    dialogue: [
      'The garden is so beautiful this time of year!',
      'I love collecting flowers for my nest.',
      'There\'s a secret passage behind the rose bush!',
      'Follow the scent of lavender — it leads home.',
    ],
    color: '#8B0000',
    accentColor: '#FF6347',
    met: false,
    active: false,
  },
  library_dog: {
    id: 'library_dog',
    name: 'Bookworm',
    breed: 'Basenji',
    trait: '📚 Scholar',
    dialogue: [
      'I love the library! So many stories to discover.',
      'There\'s a hidden passage behind the bookshelf!',
      'The librarian dog knows all the secrets of the neighborhood.',
      'Follow the scent of old paper — it leads somewhere special.',
    ],
    color: '#D2B48C',
    accentColor: '#8B4513',
    met: false,
    active: false,
  },
  market_dog: {
    id: 'market_dog',
    name: 'Baker',
    breed: 'Bichon Frise',
    trait: '🍪 Baker',
    dialogue: [
      'I bake the best treats in town!',
      'Want to learn my secret recipe? It\'s simple!',
      'The market has all sorts of interesting smells.',
      'Follow the aroma of fresh bread — it leads to the pet shop!',
    ],
    color: '#FFF8DC',
    accentColor: '#FFD700',
    met: false,
    active: false,
  },
  park_secret_dog: {
    id: 'park_secret_dog',
    name: 'Shadow',
    breed: 'Belgian Malinois',
    trait: '🌙 Stealth',
    dialogue: [
      'I know all the secret paths in the park.',
      'There\'s a hidden treasure behind the old oak tree.',
      'The moon bone only appears at night. Want to wait?',
      'Follow the shadows — they lead to the lake.',
    ],
    color: '#1a1a1a',
    accentColor: '#4a4a4a',
    met: false,
    active: false,
  },
}

export const ZONES: Record<string, Zone> = {
  suburban_streets: {
    id: 'suburban_streets',
    name: '🏘️ Suburban Streets',
    desc: 'Wide sidewalks, unfamiliar houses. The world is so big.',
    type: 'fp', // first-person
    rooms: [
      { id: 'start', name: 'Front Yard', w: 200, h: 150, d: 200, color: '#4a7a3a', exits: ['street_north', 'street_east'] },
      { id: 'street_north', name: 'North Street', w: 300, h: 120, d: 400, color: '#6a6a6a', exits: ['start', 'intersection'], features: [{type:'traffic', x:150, y:60, w:80, h:20, label:'🚗 Traffic'}] },
      { id: 'street_east', name: 'East Walk', w: 250, h: 100, d: 350, color: '#5a8a5a', exits: ['start', 'dog_park_gate'], features: [{type:'hint', x:100, y:50, w:30, h:30, label:'🦴 Bone', item:'bone'}] },
      { id: 'intersection', name: 'Street Intersection', w: 200, h: 150, d: 200, color: '#7a7a7a', exits: ['street_north', 'street_south', 'alley'], features: [{type:'choice', x:100, y:75, w:60, h:40, label:'Choose path'}] },
      { id: 'street_south', name: 'South Avenue', w: 350, h: 120, d: 300, color: '#6a6a6a', exits: ['intersection', 'apt_gate'], features: [{type:'door', x:175, y:60, w:40, h:50, label:'🚪 Door', locked:true, item:'key'}]},
      { id: 'alley', name: 'Back Alley', w: 180, h: 100, d: 300, color: '#3a3a4a', exits: ['intersection', 'shelter_entrance'], features: [{type:'cat', x:90, y:50, w:40, h:30, label:'🐱 Mean Cat'}] },
      { id: 'side_street', name: 'Side Street', w: 200, h: 100, d: 250, color: '#5a5a6a', exits: ['street_north', 'backyard'], features: [{type:'hint', x:100, y:50, w:30, h:30, label:'🐾 Scent Mark', item:'map_fragment'}] },
      { id: 'backyard', name: 'Backyard', w: 150, h: 100, d: 200, color: '#4a6a3a', exits: ['side_street'], features: [{type:'food', x:75, y:50, w:40, h:30, label:'🍖 Treat', item:'treat'}] },
      { id: 'dog_park_gate', name: 'Dog Park Gate', w: 100, h: 80, d: 100, color: '#5a9a5a', exits: ['street_east'], isEntrance: true, entranceZone: 'dog_park' },
      { id: 'shelter_entrance', name: 'Shelter Door', w: 120, h: 100, d: 120, color: '#4a4a6a', exits: ['alley'], isEntrance: true, entranceZone: 'shelter' },
      { id: 'apt_gate', name: 'Apartment Gate', w: 100, h: 80, d: 100, color: '#7a6a5a', exits: ['street_south'], isEntrance: true, entranceZone: 'apartment' },
      // New zone exits
      { id: 'pet_store_road', name: 'Pet Store Road', w: 200, h: 100, d: 250, color: '#5a5a6a', exits: ['street_north', 'pet_store_gate'], features: [{type:'hint', x:100, y:50, w:30, h:30, label:'🐾 Scent', item:'pet_shop_ticket'}] },
      { id: 'pet_store_gate', name: 'Pet Store Gate', w: 100, h: 80, d: 100, color: '#FFB6C1', exits: ['pet_store_road'], isEntrance: true, entranceZone: 'pet_store' },
      { id: 'garden_gate', name: 'Garden Gate', w: 100, h: 80, d: 100, color: '#FFB6C1', exits: ['side_street'], isEntrance: true, entranceZone: 'garden' },
      { id: 'library_gate', name: 'Library Gate', w: 100, h: 80, d: 100, color: '#D2B48C', exits: ['side_street'], isEntrance: true, entranceZone: 'library' },
      { id: 'market_gate', name: 'Market Gate', w: 100, h: 80, d: 100, color: '#FFD700', exits: ['street_south'], isEntrance: true, entranceZone: 'market' },
      { id: 'north_road', name: 'North Road', w: 250, h: 120, d: 300, color: '#6a6a6a', exits: ['street_north', 'dog_show_gate', 'lake_road'] },
      { id: 'dog_show_gate', name: 'Dog Show Gate', w: 100, h: 80, d: 100, color: '#8B4513', exits: ['north_road'], isEntrance: true, entranceZone: 'dog_show' },
      { id: 'lake_road', name: 'Lake Road', w: 200, h: 100, d: 250, color: '#4a9eff', exits: ['north_road', 'lake_entrance'] },
      { id: 'lake_entrance', name: 'Lake Shore', w: 100, h: 80, d: 100, color: '#006994', exits: ['lake_road'], isEntrance: true, entranceZone: 'lake' },
      { id: 'forest_path', name: 'Forest Path', w: 200, h: 100, d: 250, color: '#1a3a0a', exits: ['lake_road', 'forest_gate'], features: [{type:'hint', x:100, y:50, w:30, h:30, label:'🌲 Trail Mark', item:'pinecone'}] },
      { id: 'forest_gate', name: 'Forest Gate', w: 100, h: 80, d: 100, color: '#2d5a1e', exits: ['forest_path'], isEntrance: true, entranceZone: 'forest' },
      { id: 'south_coast', name: 'South Coast', w: 250, h: 120, d: 300, color: '#87CEEB', exits: ['street_south', 'beach_gate', 'mountain_path'] },
      { id: 'beach_gate', name: 'Beach Gate', w: 100, h: 80, d: 100, color: '#F4A460', exits: ['south_coast'], isEntrance: true, entranceZone: 'beach' },
      { id: 'mountain_path', name: 'Mountain Path', w: 200, h: 100, d: 250, color: '#708090', exits: ['south_coast', 'mountain_gate'], features: [{type:'hint', x:100, y:50, w:30, h:30, label:'🗺️ Trail', item:'compass_fragment'}] },
      { id: 'mountain_gate', name: 'Mountain Gate', w: 100, h: 80, d: 100, color: '#4682B4', exits: ['mountain_path'], isEntrance: true, entranceZone: 'mountain' },
      { id: 'waterfall_road', name: 'Waterfall Road', w: 200, h: 100, d: 250, color: '#2d5a1e', exits: ['forest_path', 'waterfall_gate'], features: [{type:'hint', x:100, y:50, w:30, h:30, label:'💧 Splash', item:'lake_stone'}] },
      { id: 'waterfall_gate', name: 'Waterfall Gate', w: 100, h: 80, d: 100, color: '#006994', exits: ['waterfall_road'], isEntrance: true, entranceZone: 'waterfall' },
      { id: 'secret_park_road', name: 'Secret Park Road', w: 200, h: 100, d: 250, color: '#191970', exits: ['forest_path', 'park_secret_gate'] },
      { id: 'park_secret_gate', name: 'Secret Park Gate', w: 100, h: 80, d: 100, color: '#4a4a4a', exits: ['secret_park_road'], isEntrance: true, entranceZone: 'park_secret' }
    ],
    music: 'suburban',
    hint: 'You see a squirrel. It reminds you of... something. A yard? With squirrels?'
  },
  dog_park: {
    id: 'dog_park',
    name: '🌳 Dog Park',
    desc: 'A bright, open space. Other dogs are everywhere!',
    type: 'tp',
    music: 'dog_park',
    skyColor: '#87CEEB',
    groundColor: '#4a7c3f',
    dogColor: '#d4a574',
    accentColor: '#ff6b35',
    companions: ['stray_buddy'],
    obstacles: [
      { type: 'fence', x: -8, z: -6, width: 6, height: 1.2, color: '#8B4513' },
      { type: 'fence', x: 8, z: 6, width: 5, height: 1.2, color: '#8B4513', rotation: Math.PI / 4 },
      { type: 'tree', x: -4, z: 3, height: 3, trunkColor: '#5a3a1a', leafColor: '#2d5a1e' },
      { type: 'tree', x: 5, z: -4, height: 2.5, trunkColor: '#5a3a1a', leafColor: '#3a7a2e' },
      { type: 'bench', x: 3, z: 5, width: 2, color: '#8B6914' },
      { type: 'bush', x: -6, z: -3, color: '#2d6a1e' },
      { type: 'bush', x: 7, z: -1, color: '#3a8a2e' },
    ],
    npcs: [
      {
        id: 'golden_retriever',
        name: 'Buddy',
        color: '#DAA520',
        accentColor: '#FFD700',
        x: 2,
        z: -3,
        dialogue: [
          'Woof! Welcome to the park!',
          'Home is where the fence is. Which fence?',
          'I used to live near the big oak tree!',
          'Follow the scent posts — they lead somewhere!',
        ],
      },
      {
        id: 'dog_walker',
        name: 'Sarah',
        color: '#5a7a9a',
        accentColor: '#4a9eff',
        x: -3,
        z: 4,
        dialogue: [
          'Hi there, sweetie! Are you lost?',
          'Have you seen a husky around here?',
          'The shelter is this way! *points*',
        ],
      },
    ],
    features: [
      { type: 'water_bowl', x: 6, z: 3, id: 'water_bowl', label: '💧 Water Bowl' },
      { type: 'fire_hydrant', x: -5, z: -2, id: 'fire_hydrant', label: '🚒 Fire Hydrant' },
      { type: 'scent_post', x: 0, z: 7, id: 'scent_post', label: '🐾 Scent Post' },
      { type: 'treasure', x: -7, z: 5, id: 'treasure_1', label: '✨ Scent Clue' },
      { type: 'return_gate', x: 0, z: -8, id: 'park_exit', label: '🚪 Exit to Streets' },
    ],
    returnZone: 'suburban_streets',
    hint: 'A big dog says "Home is where the fence is." Fences are everywhere... but which fence?',
  },
  apartment: {
    id: 'apartment',
    name: '🏠 Random Apartment',
    desc: 'You found the door open. Inside: smells, sounds, and a TV that barks back.',
    type: 'fp',
    rooms: [
      { id: 'apt_entrance', name: 'Entryway', w: 120, h: 80, d: 150, color: '#8a7a6a', exits: ['apt_living', 'apt_kitchen'], isEntrance: true, entranceZone: 'suburban_streets' },
      { id: 'apt_living', name: 'Living Room', w: 200, h: 100, d: 180, color: '#7a6a5a', exits: ['apt_entrance', 'apt_bedroom'], features: [{type:'tv', x:100, y:50, w:60, h:40, label:'📺 TV (barks back)'}] },
      { id: 'apt_kitchen', name: 'Kitchen', w: 150, h: 90, d: 120, color: '#9a8a7a', exits: ['apt_entrance', 'apt_bathroom'], features: [{type:'food', x:75, y:45, w:40, h:30, label:'🍖 Food', item:'treat'}] },
      { id: 'apt_bedroom', name: 'Bedroom', w: 160, h: 90, d: 140, color: '#6a5a7a', exits: ['apt_living', 'apt_bathroom'], features: [{type:'hint', x:80, y:45, w:50, h:30, label:'🧸 Toy', item:'toy'}] },
      { id: 'apt_bathroom', name: 'Bathroom', w: 100, h: 80, d: 100, color: '#8a8a9a', exits: ['apt_kitchen', 'apt_bedroom'], features: [{type:'water_bowl', x:50, y:40, w:30, h:30, label:'💧 Water Bowl'}] },
      { id: 'apt_balcony', name: 'Balcony', w: 120, h: 70, d: 80, color: '#5a7a5a', exits: ['apt_living'], features: [{type:'hint', x:60, y:35, w:40, h:30, label:'🌳 View', item:'tree_clue'}] }
    ],
    music: 'apartment',
    hint: 'Under the bed: a red ball. You remember throwing this. Someone threw this. For YOU.',
    returnZone: 'suburban_streets',
  },
  shelter: {
    id: 'shelter',
    name: '🏥 Animal Shelter',
    desc: 'Cages, sounds, and hope. Maybe some dogs here know the way home.',
    type: 'fp',
    rooms: [
      { id: 'shelter_lobby', name: 'Lobby', w: 200, h: 100, d: 150, color: '#8a8a9a', exits: ['shelter_kennels', 'shelter_office', 'shelter_exit', 'shelter_garden'] },
      { id: 'shelter_exit', name: 'Exit Door', w: 80, h: 60, d: 80, color: '#6a6a7a', exits: ['shelter_lobby', 'shelter_to_neighborhood'] },
      { id: 'shelter_to_neighborhood', name: 'Side Gate', w: 60, h: 50, d: 60, color: '#5a5a6a', exits: ['shelter_lobby'], isEntrance: true, entranceZone: 'neighborhood' },
      { id: 'shelter_kennels', name: 'Kennels', w: 300, h: 120, d: 200, color: '#7a7a8a', exits: ['shelter_lobby'], features: [{type:'dog_friend', x:150, y:60, w:50, h:40, label:'🐕 New Friend', item:'friend'}] },
      { id: 'shelter_office', name: 'Office', w: 120, h: 80, d: 100, color: '#6a6a7a', exits: ['shelter_lobby'], features: [{type:'hint', x:60, y:40, w:40, h:30, label:'📋 Poster', item:'map_fragment'}] },
      { id: 'shelter_garden', name: 'Garden', w: 150, h: 100, d: 120, color: '#4a7a3a', exits: ['shelter_lobby'], features: [{type:'food', x:75, y:50, w:40, h:30, label:'🍖 Treat', item:'treat'}] },
      { id: 'shelter_vet', name: 'Vet Room', w: 100, h: 80, d: 100, color: '#9a9aaa', exits: ['shelter_lobby'], features: [{type:'hint', x:50, y:40, w:40, h:30, label:'📋 Medical Record', item:'collar'}] }
    ],
    music: 'shelter',
    hint: 'A poster shows a lost dog. It looks... familiar. But it could be anyone.',
    returnZone: 'suburban_streets',
  },
  neighborhood: {
    id: 'neighborhood',
    name: '🏡 The Neighborhood',
    desc: 'The streets feel familiar. You\'re close. You can feel it.',
    type: 'fp',
    rooms: [
      { id: 'neighborhood_entrance', name: 'Side Gate', w: 80, h: 60, d: 80, color: '#5a5a5a', exits: ['neighborhood_start'], isEntrance: true, entranceZone: 'shelter' },
      { id: 'neighborhood_start', name: 'Street Corner', w: 250, h: 120, d: 200, color: '#5a8a5a', exits: ['neighborhood_main', 'neighborhood_park', 'neighborhood_entrance', 'neighborhood_library'] },
      { id: 'neighborhood_main', name: 'Main Street', w: 350, h: 140, d: 300, color: '#6a6a6a', exits: ['neighborhood_start', 'neighborhood_home', 'neighborhood_market'], features: [{type:'person', x:175, y:70, w:40, h:60, label:'👤 "Have you seen a dog like him?"'}] },
      { id: 'neighborhood_park', name: 'Local Park', w: 200, h: 100, d: 180, color: '#4a7a3a', exits: ['neighborhood_start'], features: [{type:'hint', x:100, y:50, w:60, h:30, label:'🌳 Old Tree', item:'tree_clue'}] },
      { id: 'neighborhood_home', name: 'The House', w: 180, h: 100, d: 150, color: '#8a7a5a', exits: ['neighborhood_main'], isHome: true, isEntrance: true, entranceZone: 'home', features: [{type:'home', x:90, y:50, w:60, h:60, label:'🏠 Home'}] },
      { id: 'neighborhood_library', name: 'Library', w: 140, h: 90, d: 120, color: '#7a6a5a', exits: ['neighborhood_start'], features: [{type:'hint', x:70, y:45, w:50, h:30, label:'📚 Lost Dog Poster', item:'photo'}] },
      { id: 'neighborhood_market', name: 'Market', w: 200, h: 110, d: 160, color: '#8a7a4a', exits: ['neighborhood_main'], features: [{type:'food', x:100, y:55, w:50, h:30, label:'🍖 Food Stand', item:'treat'}] }
    ],
    music: 'home',
    hint: 'The gate. It\'s the same gate. You remember this one. This is it.',
    returnZone: 'suburban_streets',
  },
  home: {
    id: 'home',
    name: '🏡 Home',
    desc: 'You made it! The golden gate stands before you. This is where you belong.',
    type: 'fp',
    rooms: [
      { id: 'home_gate', name: 'Golden Gate', w: 100, h: 80, d: 80, color: '#d4a017', exits: ['home_yard'], isEntrance: true, entranceZone: 'neighborhood' },
      { id: 'home_yard', name: 'Backyard', w: 250, h: 150, d: 200, color: '#4a8a3a', exits: ['home_gate', 'home_door'], features: [{type:'celebration', x:125, y:75, w:80, h:60, label:'🎉 Welcome Home!'}] },
      { id: 'home_door', name: 'Front Door', w: 80, h: 100, d: 60, color: '#8a6a3a', exits: ['home_yard'], isHome: true, features: [{type:'home', x:40, y:50, w:60, h:60, label:'🏠 Home'}] }
    ],
    music: 'home',
    hint: 'You\'re home. You\'re finally home.',
    returnZone: 'suburban_streets',
  },
  // New zones
  lake: {
    id: 'lake',
    name: '🌊 The Lake',
    desc: 'A peaceful lake surrounded by trees. The water sparkles in the sunlight.',
    type: 'tp',
    music: 'lake',
    skyColor: '#87CEEB',
    groundColor: '#2d5a1e',
    dogColor: '#4a9eff',
    accentColor: '#006994',
    companions: ['lake_dog'],
    obstacles: [
      { type: 'tree', x: -5, z: 4, height: 4, trunkColor: '#5a3a1a', leafColor: '#2d5a1e' },
      { type: 'tree', x: 6, z: -3, height: 3.5, trunkColor: '#5a3a1a', leafColor: '#3a7a2e' },
      { type: 'bush', x: -7, z: -5, color: '#2d6a1e' },
      { type: 'bench', x: 4, z: 6, width: 2, color: '#8B6914' },
      { type: 'fence', x: 0, z: 8, width: 8, height: 1, color: '#8B4513' },
    ],
    npcs: [
      {
        id: 'lake_dog_npc',
        name: 'River',
        color: '#D2691E',
        accentColor: '#FFD700',
        x: 3,
        z: -2,
        dialogue: [
          'The lake is beautiful this time of year!',
          'I used to swim here every day with my human.',
          'There\'s a secret path behind the waterfall. Want to see?',
          'Follow the water — it leads somewhere special.',
        ],
      },
    ],
    features: [
      { type: 'water', x: 0, z: 0, id: 'lake_center', label: '🌊 Lake Center' },
      { type: 'scent_post', x: -6, z: 5, id: 'lake_scent', label: '🐾 Scent Post' },
      { type: 'treasure', x: 7, z: -6, id: 'lake_treasure', label: '✨ Hidden Treasure' },
      { type: 'bridge', x: 5, z: 3, id: 'wooden_bridge', label: '🌉 Wooden Bridge' },
      { type: 'return_gate', x: 0, z: -8, id: 'lake_exit', label: '🚪 Exit to Streets' },
    ],
    returnZone: 'suburban_streets',
    hint: 'The water sparkles. You remember swimming here once. With your human.',
  },
  pet_store: {
    id: 'pet_store',
    name: '🏪 Pet Paradise',
    desc: 'A colorful pet shop filled with treats, toys, and friendly animals.',
    type: 'fp',
    rooms: [
      { id: 'pet_entrance', name: 'Entrance', w: 120, h: 80, d: 150, color: '#FFB6C1', exits: ['pet_main', 'pet_back'], isEntrance: true, entranceZone: 'suburban_streets' },
      { id: 'pet_main', name: 'Main Hall', w: 200, h: 100, d: 180, color: '#FF69B4', exits: ['pet_entrance', 'pet_treats', 'pet_toys', 'pet_grooming'], features: [{type:'pet_shop', x:100, y:50, w:60, h:40, label:'🏪 Pet Paradise'}] },
      { id: 'pet_treats', name: 'Treat Room', w: 150, h: 90, d: 120, color: '#FFD700', exits: ['pet_main'], features: [{type:'food', x:75, y:45, w:40, h:30, label:'🍪 Treats', item:'pet_shop_treat'}] },
      { id: 'pet_toys', name: 'Toy Room', w: 160, h: 90, d: 140, color: '#FF69B4', exits: ['pet_main'], features: [{type:'hint', x:80, y:45, w:50, h:30, label:'🧸 Toys', item:'pet_shop_ticket'}] },
      { id: 'pet_grooming', name: 'Grooming Room', w: 100, h: 80, d: 100, color: '#FFF0F5', exits: ['pet_main'], features: [{type:'water', x:50, y:40, w:30, h:30, label:'💧 Water Bowl'}] },
      { id: 'pet_back', name: 'Back Room', w: 120, h: 70, d: 80, color: '#FFB6C1', exits: ['pet_entrance'], features: [{type:'secret_passage', x:60, y:35, w:40, h:30, label:'🔑 Secret Passage', item:'secret_key'}] }
    ],
    music: 'pet_store',
    hint: 'The smell of treats is overwhelming. Your human used to bring you here!',
  },
  dog_show: {
    id: 'dog_show',
    name: '🏆 Dog Show Arena',
    desc: 'A grand arena where dogs compete for glory. The air is filled with excitement.',
    type: 'tp',
    music: 'dog_show',
    skyColor: '#87CEEB',
    groundColor: '#8B4513',
    dogColor: '#FFD700',
    accentColor: '#FF6347',
    companions: ['dog_show_dog'],
    obstacles: [
      { type: 'fence', x: -10, z: -8, width: 8, height: 1.5, color: '#8B4513' },
      { type: 'fence', x: 10, z: 8, width: 8, height: 1.5, color: '#8B4513' },
      { type: 'tree', x: -6, z: 5, height: 4, trunkColor: '#5a3a1a', leafColor: '#2d5a1e' },
      { type: 'tree', x: 7, z: -6, height: 3.5, trunkColor: '#5a3a1a', leafColor: '#3a7a2e' },
      { type: 'bench', x: 5, z: 7, width: 3, color: '#8B6914' },
      { type: 'bench', x: -8, z: -5, width: 3, color: '#8B6914' },
    ],
    npcs: [
      {
        id: 'dog_show_dog_npc',
        name: 'Champion',
        color: '#FFFFFF',
        accentColor: '#FFD700',
        x: 2,
        z: -3,
        dialogue: [
          'I\'ve won every dog show in the region!',
          'Would you like to compete? I can train you!',
          'The secret to winning is confidence and treats!',
          'Follow the crowd — they all head to the park!',
        ],
      },
    ],
    features: [
      { type: 'dog_show', x: 0, z: 0, id: 'show_ring', label: '🏆 Show Ring' },
      { type: 'scent_post', x: -8, z: 6, id: 'show_scent', label: '🐾 Scent Post' },
      { type: 'treasure', x: 9, z: -7, id: 'show_treasure', label: '✨ Trophy Case' },
      { type: 'lure', x: 6, z: 4, id: 'treat_lure', label: '🍖 Treat Lure' },
      { type: 'return_gate', x: 0, z: -8, id: 'show_exit', label: '🚪 Exit to Streets' },
    ],
    returnZone: 'suburban_streets',
    hint: 'The roar of the crowd excites you. You remember winning here once.',
  },
  forest: {
    id: 'forest',
    name: '🌲 The Deep Forest',
    desc: 'A dense forest with towering trees. Sunlight filters through the canopy.',
    type: 'tp',
    music: 'forest',
    skyColor: '#2F4F4F',
    groundColor: '#1a3a0a',
    dogColor: '#8B4513',
    accentColor: '#D2691E',
    companions: ['forest_dog'],
    obstacles: [
      { type: 'tree', x: -8, z: 6, height: 5, trunkColor: '#5a3a1a', leafColor: '#1a3a0a' },
      { type: 'tree', x: 7, z: -5, height: 4.5, trunkColor: '#5a3a1a', leafColor: '#2d5a1e' },
      { type: 'tree', x: -3, z: -7, height: 4, trunkColor: '#5a3a1a', leafColor: '#3a7a2e' },
      { type: 'bush', x: 6, z: 7, color: '#2d6a1e' },
      { type: 'bush', x: -7, z: -6, color: '#3a8a2e' },
      { type: 'fence', x: 0, z: 9, width: 6, height: 1.2, color: '#8B4513' },
    ],
    npcs: [
      {
        id: 'forest_dog_npc',
        name: 'Forest',
        color: '#8B4513',
        accentColor: '#D2691E',
        x: -2,
        z: 4,
        dialogue: [
          'The forest is vast and full of wonders!',
          'I can smell home from here! Well, almost.',
          'Watch out for the storm drain ahead!',
          'The cave behind the waterfall holds secrets.',
        ],
      },
    ],
    features: [
      { type: 'fountain', x: 0, z: 0, id: 'forest_fountain', label: '💧 Forest Spring' },
      { type: 'scent_post', x: -9, z: 7, id: 'forest_scent', label: '🐾 Scent Post' },
      { type: 'treasure', x: 8, z: -8, id: 'forest_treasure', label: '✨ Cave Entrance' },
      { type: 'lure', x: 5, z: 6, id: 'forest_lure', label: '🍖 Food Scent' },
      { type: 'return_gate', x: 0, z: -8, id: 'forest_exit', label: '🚪 Exit to Streets' },
      { type: 'cave_entrance', x: 10, z: 0, id: 'cave_path', label: '🕳️ Cave Entrance' },
    ],
    returnZone: 'suburban_streets',
    hint: 'The forest smells like home. Your human used to bring you here for walks.',
  },
  beach: {
    id: 'beach',
    name: '🏖️ Sandy Beach',
    desc: 'A wide sandy beach with crashing waves. Seagulls cry overhead.',
    type: 'tp',
    music: 'beach',
    skyColor: '#87CEEB',
    groundColor: '#F4A460',
    dogColor: '#4682B4',
    accentColor: '#87CEEB',
    companions: ['beach_dog'],
    obstacles: [
      { type: 'tree', x: -6, z: 5, height: 3, trunkColor: '#5a3a1a', leafColor: '#2d5a1e' },
      { type: 'tree', x: 7, z: -4, height: 2.5, trunkColor: '#5a3a1a', leafColor: '#3a7a2e' },
      { type: 'bush', x: -8, z: -6, color: '#2d6a1e' },
      { type: 'bench', x: 4, z: 7, width: 2, color: '#8B6914' },
    ],
    npcs: [
      {
        id: 'beach_dog_npc',
        name: 'Surfer',
        color: '#4682B4',
        accentColor: '#87CEEB',
        x: 3,
        z: -2,
        dialogue: [
          'The beach is my happy place!',
          'I found a treasure map here once! Want to see?',
          'The waves bring all sorts of interesting things.',
          'Follow the seagulls — they know where the good stuff is!',
        ],
      },
    ],
    features: [
      { type: 'water', x: 0, z: -8, id: 'ocean', label: '🌊 Ocean' },
      { type: 'scent_post', x: -7, z: 6, id: 'beach_scent', label: '🐾 Scent Post' },
      { type: 'treasure', x: 8, z: -7, id: 'beach_treasure', label: '✨ Buried Treasure' },
      { type: 'lure', x: 5, z: 5, id: 'beach_lure', label: '🍖 Fish Scent' },
      { type: 'return_gate', x: 0, z: -8, id: 'beach_exit', label: '🚪 Exit to Streets' },
    ],
    returnZone: 'suburban_streets',
    hint: 'The sand feels familiar. Your human used to throw the ball here.',
  },
  mountain: {
    id: 'mountain',
    name: '⛰️ Mountain Peak',
    desc: 'A towering mountain with rocky paths. The view from the top is breathtaking.',
    type: 'tp',
    music: 'mountain',
    skyColor: '#4682B4',
    groundColor: '#708090',
    dogColor: '#2F4F4F',
    accentColor: '#708090',
    companions: ['mountain_dog'],
    obstacles: [
      { type: 'tree', x: -7, z: 5, height: 4, trunkColor: '#5a3a1a', leafColor: '#1a3a0a' },
      { type: 'tree', x: 8, z: -6, height: 3.5, trunkColor: '#5a3a1a', leafColor: '#2d5a1e' },
      { type: 'bush', x: -9, z: -7, color: '#2d6a1e' },
      { type: 'fence', x: 0, z: 10, width: 7, height: 1.5, color: '#8B4513' },
    ],
    npcs: [
      {
        id: 'mountain_dog_npc',
        name: 'Peak',
        color: '#2F4F4F',
        accentColor: '#708090',
        x: -3,
        z: 4,
        dialogue: [
          'The mountain path is steep but worth it!',
          'I\'ve seen dogs go up there and come back with stories.',
          'The cave at the top holds ancient treasures.',
          'Watch your step on the rocky paths!',
        ],
      },
    ],
    features: [
      { type: 'fountain', x: 0, z: 0, id: 'mountain_spring', label: '💧 Mountain Spring' },
      { type: 'scent_post', x: -8, z: 7, id: 'mountain_scent', label: '🐾 Scent Post' },
      { type: 'treasure', x: 9, z: -8, id: 'mountain_treasure', label: '✨ Cave Treasure' },
      { type: 'lure', x: 6, z: 6, id: 'mountain_lure', label: '🍖 Food Scent' },
      { type: 'return_gate', x: 0, z: -8, id: 'mountain_exit', label: '🚪 Exit to Streets' },
    ],
    returnZone: 'suburban_streets',
    hint: 'The mountain air is crisp. Your human used to hike here with you.',
  },
  garden: {
    id: 'garden',
    name: '🌺 Secret Garden',
    desc: 'A hidden garden filled with beautiful flowers and peaceful paths.',
    type: 'fp',
    rooms: [
      { id: 'garden_entrance', name: 'Garden Gate', w: 120, h: 80, d: 150, color: '#FF69B4', exits: ['garden_main', 'garden_flowers'], isEntrance: true, entranceZone: 'suburban_streets' },
      { id: 'garden_main', name: 'Main Path', w: 200, h: 100, d: 180, color: '#FFB6C1', exits: ['garden_entrance', 'garden_fountain', 'garden_rose'], features: [{type:'fountain', x:100, y:50, w:60, h:40, label:'⛲ Fountain'}] },
      { id: 'garden_flowers', name: 'Flower Bed', w: 150, h: 90, d: 120, color: '#FFD700', exits: ['garden_main'], features: [{type:'hint', x:75, y:45, w:50, h:30, label:'🌸 Flowers', item:'flower'}] },
      { id: 'garden_fountain', name: 'Fountain Area', w: 160, h: 90, d: 140, color: '#87CEEB', exits: ['garden_main'], features: [{type:'water', x:80, y:45, w:40, h:30, label:'💧 Fountain'}] },
      { id: 'garden_rose', name: 'Rose Garden', w: 100, h: 80, d: 100, color: '#FF6347', exits: ['garden_main'], features: [{type:'secret_passage', x:50, y:40, w:40, h:30, label:'🔑 Rose Passage', item:'secret_key'}] }
    ],
    music: 'garden',
    hint: 'The roses smell like your human\'s garden. You remember playing here.',
    returnZone: 'suburban_streets',
  },
  library: {
    id: 'library',
    name: '📚 Old Library',
    desc: 'A quiet library filled with books and mysterious secrets.',
    type: 'fp',
    rooms: [
      { id: 'library_entrance', name: 'Entrance Hall', w: 120, h: 80, d: 150, color: '#D2B48C', exits: ['library_main', 'library_stacks'], isEntrance: true, entranceZone: 'suburban_streets' },
      { id: 'library_main', name: 'Main Hall', w: 200, h: 100, d: 180, color: '#8B4513', exits: ['library_entrance', 'library_reference', 'library_special'], features: [{type:'person', x:100, y:50, w:40, h:60, label:'👤 Librarian Dog'}] },
      { id: 'library_stacks', name: 'Book Stacks', w: 150, h: 90, d: 120, color: '#654321', exits: ['library_main'], features: [{type:'hint', x:75, y:45, w:50, h:30, label:'📚 Books', item:'letter'}] },
      { id: 'library_reference', name: 'Reference Room', w: 160, h: 90, d: 140, color: '#8B6914', exits: ['library_main'], features: [{type:'hint', x:80, y:45, w:50, h:30, label:'🗺️ Maps', item:'treasure_map'}] },
      { id: 'library_special', name: 'Special Collection', w: 100, h: 80, d: 100, color: '#4a2a0a', exits: ['library_main'], features: [{type:'secret_passage', x:50, y:40, w:40, h:30, label:'🔑 Hidden Door', item:'secret_key'}] }
    ],
    music: 'library',
    hint: 'The books smell like home. Your human used to read to you here.',
    returnZone: 'suburban_streets',
  },
  market: {
    id: 'market',
    name: '🏪 Town Market',
    desc: 'A bustling market with vendors selling treats, toys, and more.',
    type: 'fp',
    rooms: [
      { id: 'market_entrance', name: 'Market Gate', w: 120, h: 80, d: 150, color: '#FFD700', exits: ['market_main', 'market_food'], isEntrance: true, entranceZone: 'suburban_streets' },
      { id: 'market_main', name: 'Main Market', w: 200, h: 100, d: 180, color: '#FF69B4', exits: ['market_entrance', 'market_toys', 'market_treats'], features: [{type:'person', x:100, y:50, w:40, h:60, label:'👤 Market Vendor'}] },
      { id: 'market_food', name: 'Food Stalls', w: 150, h: 90, d: 120, color: '#FFB6C1', exits: ['market_main'], features: [{type:'food', x:75, y:45, w:40, h:30, label:'🍖 Food', item:'pizza_crust'}] },
      { id: 'market_toys', name: 'Toy Shop', w: 160, h: 90, d: 140, color: '#87CEEB', exits: ['market_main'], features: [{type:'hint', x:80, y:45, w:50, h:30, label:'🧸 Toys', item:'dog_show_ribbon'}] },
      { id: 'market_treats', name: 'Treat Stand', w: 100, h: 80, d: 100, color: '#FFD700', exits: ['market_main'], features: [{type:'food', x:50, y:40, w:40, h:30, label:'🍪 Treats', item:'cookie'}] }
    ],
    music: 'market',
    hint: 'The smells of the market remind you of days spent shopping with your human.',
    returnZone: 'suburban_streets',
  },
  cave: {
    id: 'cave',
    name: '🕳️ Crystal Cave',
    desc: 'A mysterious cave filled with glowing crystals and ancient secrets.',
    type: 'fp',
    rooms: [
      { id: 'cave_entrance', name: 'Cave Entrance', w: 120, h: 80, d: 150, color: '#2F4F4F', exits: ['cave_main', 'cave_deep'], isEntrance: true, entranceZone: 'forest' },
      { id: 'cave_main', name: 'Main Cave', w: 200, h: 100, d: 180, color: '#4682B4', exits: ['cave_entrance', 'cave_crystal', 'cave_deep'], features: [{type:'fountain', x:100, y:50, w:60, h:40, label:'💧 Crystal Spring'}] },
      { id: 'cave_crystal', name: 'Crystal Chamber', w: 150, h: 90, d: 120, color: '#87CEEB', exits: ['cave_main'], features: [{type:'treasure', x:75, y:45, w:50, h:30, label:'💎 Crystal Treasure', item:'cave_crystal'}] },
      { id: 'cave_deep', name: 'Deep Cave', w: 160, h: 90, d: 140, color: '#1a1a2e', exits: ['cave_main'], features: [{type:'secret_passage', x:80, y:45, w:50, h:30, label:'🔑 Secret Exit', item:'secret_key'}] }
    ],
    music: 'cave',
    hint: 'The crystals glow with a familiar light. You remember this place.',
    returnZone: 'suburban_streets',
  },
  waterfall: {
    id: 'waterfall',
    name: '💧 Waterfall Falls',
    desc: 'A majestic waterfall cascading into a peaceful pool below.',
    type: 'tp',
    music: 'waterfall',
    skyColor: '#87CEEB',
    groundColor: '#2d5a1e',
    dogColor: '#4a9eff',
    accentColor: '#006994',
    companions: ['lake_dog'],
    obstacles: [
      { type: 'tree', x: -6, z: 5, height: 4, trunkColor: '#5a3a1a', leafColor: '#2d5a1e' },
      { type: 'tree', x: 7, z: -4, height: 3.5, trunkColor: '#5a3a1a', leafColor: '#3a7a2e' },
      { type: 'bush', x: -8, z: -6, color: '#2d6a1e' },
      { type: 'bench', x: 4, z: 7, width: 2, color: '#8B6914' },
    ],
    npcs: [
      {
        id: 'waterfall_dog_npc',
        name: 'River',
        color: '#D2691E',
        accentColor: '#FFD700',
        x: 2,
        z: -3,
        dialogue: [
          'The waterfall is beautiful this time of year!',
          'There\'s a secret path behind the falls. Want to see?',
          'The pool below holds ancient treasures.',
          'Follow the water — it leads somewhere special.',
        ],
      },
    ],
    features: [
      { type: 'water', x: 0, z: 0, id: 'waterfall_pool', label: '💧 Waterfall Pool' },
      { type: 'scent_post', x: -7, z: 6, id: 'waterfall_scent', label: '🐾 Scent Post' },
      { type: 'treasure', x: 8, z: -7, id: 'waterfall_treasure', label: '✨ Hidden Treasure' },
      { type: 'lure', x: 5, z: 5, id: 'waterfall_lure', label: '🍖 Fish Scent' },
      { type: 'return_gate', x: 0, z: -8, id: 'waterfall_exit', label: '🚪 Exit to Streets' },
    ],
    returnZone: 'suburban_streets',
    hint: 'The sound of the waterfall is soothing. You remember playing here with your human.',
  },
  park_secret: {
    id: 'park_secret',
    name: '🌙 Secret Park',
    desc: 'A hidden park that only appears at night. Full of magical surprises.',
    type: 'tp',
    music: 'park_secret',
    skyColor: '#191970',
    groundColor: '#2d5a1e',
    dogColor: '#1a1a1a',
    accentColor: '#4a4a4a',
    companions: ['park_secret_dog'],
    obstacles: [
      { type: 'tree', x: -7, z: 5, height: 4, trunkColor: '#5a3a1a', leafColor: '#1a3a0a' },
      { type: 'tree', x: 8, z: -6, height: 3.5, trunkColor: '#5a3a1a', leafColor: '#2d5a1e' },
      { type: 'bush', x: -9, z: -7, color: '#2d6a1e' },
      { type: 'bench', x: 5, z: 7, width: 2, color: '#8B6914' },
    ],
    npcs: [
      {
        id: 'park_secret_dog_npc',
        name: 'Shadow',
        color: '#1a1a1a',
        accentColor: '#4a4a4a',
        x: -2,
        z: 4,
        dialogue: [
          'I know all the secret paths in the park.',
          'There\'s a hidden treasure behind the old oak tree.',
          'The moon bone only appears at night. Want to wait?',
          'Follow the shadows — they lead to the lake.',
        ],
      },
    ],
    features: [
      { type: 'fountain', x: 0, z: 0, id: 'secret_fountain', label: '🌙 Moon Fountain' },
      { type: 'scent_post', x: -8, z: 6, id: 'secret_scent', label: '🐾 Scent Post' },
      { type: 'treasure', x: 9, z: -8, id: 'secret_treasure', label: '✨ Moon Treasure' },
      { type: 'lure', x: 6, z: 6, id: 'secret_lure', label: '🍖 Moon Treat' },
      { type: 'return_gate', x: 0, z: -8, id: 'park_secret_exit', label: '🚪 Exit to Streets' },
    ],
    returnZone: 'suburban_streets',
    hint: 'The park glows under the moonlight. Your human used to bring you here at night.',
  }
}

export const ITEMS: Record<string, Item> = {
  bone: { name: '🦴 Bone', desc: 'A good bone. Smells familiar.', category: 'comfort' },
  treat: { name: '🍖 Treat', desc: 'Delicious! Restores happiness.', category: 'food' },
  toy: { name: '🧸 Toy', desc: 'A red ball. You remember this.', category: 'comfort' },
  key: { name: '🗝️ Key', desc: 'A small metal key.', category: 'key' },
  map_fragment: { name: '📋 Map Fragment', desc: 'Part of a map. Shows a street.', category: 'clue' },
  tree_clue: { name: '🌳 Tree Clue', desc: 'A tree you remember. Marked with a scratch.', category: 'clue' },
  friend: { name: '🐕 Friend', desc: 'A new companion!', category: 'comfort' },
  food: { name: '🍎 Food', desc: 'A snack for the road.', category: 'food' },
  collar_piece: { name: '📿 Collar Piece', desc: 'A piece of your collar. You recognize this.', category: 'key' },
  leash: { name: '🔗 Leash', desc: 'A red leash. Your human used this.', category: 'key' },
  collar: { name: '🎀 Collar', desc: 'Your collar! You remember wearing this.', category: 'key' },
  medal: { name: '🏅 Medal', desc: 'A dog show medal. You won this once.', category: 'comfort' },
  bone_necklace: { name: '🦴 Bone Necklace', desc: 'A necklace made of bones. Creepy but familiar.', category: 'comfort' },
  photo: { name: '📸 Photo', desc: 'A photo of you and your human. You miss them.', category: 'story' },
  blanket: { name: '🧶 Blanket', desc: 'A piece of your favorite blanket. Smells like home.', category: 'comfort' },
  water_bottle: { name: '💧 Water Bottle', desc: 'Half-full water. Perfect for a hot day.', category: 'comfort' },
  squirrel_dog: { name: '🐿️ Squirrel Toy', desc: 'A toy squirrel. You love this one.', category: 'comfort' },
  tennis_ball: { name: '🎾 Tennis Ball', desc: 'A slobbery tennis ball. Classic.', category: 'comfort' },
  dog_tag: { name: '🏷️ Dog Tag', desc: 'Your dog tag with your name on it.', category: 'key' },
  treat_bag: { name: '🥡 Treat Bag', desc: 'An open bag of treats. Jackpot!', category: 'food' },
  puzzle_piece: { name: '🧩 Puzzle Piece', desc: 'Part of a dog show puzzle. Shows a route.', category: 'crafting' },
  lake_stone: { name: '🪨 Lake Stone', desc: 'Smooth stone from the lake shore. Shiny.', category: 'crafting' },
  pet_shop_ticket: { name: '🎫 Pet Shop Ticket', desc: 'Admits you to the pet shop. Smells like treats.', category: 'crafting' },
  dog_show_ribbon: { name: '🎀 Dog Show Ribbon', desc: 'Blue ribbon from the dog show. You earned it!', category: 'crafting' },
  compass_fragment: { name: '🧭 Compass Fragment', desc: 'Half a compass. Points toward home.', category: 'crafting' },
  magic_bone: { name: '✨ Magic Bone', desc: 'Glows faintly. Smells like adventure.', category: 'crafting' },
  treasure_map: { name: '🗺️ Treasure Map', desc: 'Shows where secrets are hidden.', category: 'clue' },
  secret_key: { name: '🔑 Secret Key', desc: 'Opens hidden passages.', category: 'key' },
  golden_bone: { name: '🦴 Golden Bone', desc: 'The legendary golden bone. Pure magic.', category: 'rare' },
  warm_blanket: { name: '🧶 Warm Blanket', desc: 'Smells like your human. Comforting.', category: 'comfort' },
  favorite_toy: { name: '🧸 Favorite Toy', desc: 'Your old stuffed animal. Safe.', category: 'comfort' },
  comfort_bell: { name: '🔔 Comfort Bell', desc: 'Rings when near home.', category: 'comfort' },
  lake_crystal: { name: '💎 Lake Crystal', desc: 'Sparkles in the water. Magical.', category: 'rare' },
  pet_shop_treat: { name: '🍪 Pet Shop Treat', desc: 'Fresh from the bakery. Delicious!', category: 'food' },
  dog_show_trophy: { name: '🏆 Dog Show Trophy', desc: 'You won first place! Well done.', category: 'collectible' },
  shiny_rock: { name: '✨ Shiny Rock', desc: 'Glistens in the sun. Pretty.', category: 'collectible' },
  feather: { name: '🪶 Feather', desc: 'Soft and colorful. From a bird.', category: 'collectible' },
  pinecone: { name: '🌲 Pinecone', desc: 'From the forest. Smells like trees.', category: 'collectible' },
  flower: { name: '🌸 Flower', desc: 'Sweet smelling. Your human loved flowers.', category: 'collectible' },
  leaf: { name: '🍂 Leaf', desc: 'Autumn colored. Beautiful.', category: 'collectible' },
  shell: { name: '🐚 Shell', desc: 'From the lake shore. Smooth.', category: 'collectible' },
  home_photo: { name: '📸 Home Photo', desc: 'A photo of your home. You remember this place.', category: 'story' },
  collar_buckle: { name: '🔗 Collar Buckle', desc: 'Part of your collar. You recognize it.', category: 'key' },
  dog_license: { name: '📋 Dog License', desc: 'Your official dog license. Real proof of home.', category: 'key' },
  rainbow_bone: { name: '🌈 Rainbow Bone', desc: 'Shimmers with all colors. Legendary!', category: 'rare' },
  moon_bone: { name: '🌙 Moon Bone', desc: 'Glows in the dark. Magical.', category: 'rare' },
  star_bone: { name: '⭐ Star Bone', desc: 'Sparkles like a star. Rare!', category: 'rare' },
  pizza_crust: { name: '🍕 Pizza Crust', desc: 'Found on the sidewalk. Smells good.', category: 'food' },
  hot_dog: { name: '🌭 Hot Dog', desc: 'A real hot dog! Wait... is that...?', category: 'food' },
  ice_cream: { name: '🍦 Ice Cream', desc: 'Still frozen! Sweet and cold.', category: 'food' },
  cookie: { name: '🍪 Cookie', desc: 'Chocolate chip. Perfect.', category: 'food' },
  cupcake: { name: '🧁 Cupcake', desc: 'With sprinkles. Festive!', category: 'food' },
  donut: { name: '🍩 Donut', desc: 'Glazed. Simple perfection.', category: 'food' },
  flashlight: { name: '🔦 Flashlight', desc: 'Lights up dark places. Useful.', category: 'utility' },
  rope: { name: '🪢 Rope', desc: 'Tough and long. Can tie things.', category: 'utility' },
  magnet: { name: '🧲 Magnet', desc: 'Attracts metal. Weirdly useful.', category: 'utility' },
  umbrella: { name: '☂️ Umbrella', desc: 'Keeps you dry in rain. Comforting.', category: 'utility' },
  letter: { name: '✉️ Letter', desc: 'A letter addressed to you. From your human?', category: 'story' },
  diary_page: { name: '📄 Diary Page', desc: 'Your human wrote about you here. Sweet.', category: 'story' },
  forest_mushroom: { name: '🍄 Forest Mushroom', desc: 'Colorful and strange. Don\'t eat it.', category: 'collectible' },
  cave_crystal: { name: '💎 Cave Crystal', desc: 'Glowing from within. Magical.', category: 'rare' },
  beach_shell: { name: '🐚 Beach Shell', desc: 'From the shore. Smooth and pretty.', category: 'collectible' },
  mountain_rock: { name: '🪨 Mountain Rock', desc: 'Heavy and ancient. Powerful.', category: 'collectible' },
  garden_flower: { name: '🌺 Garden Flower', desc: 'Bright and beautiful. Your human grew these.', category: 'collectible' },
  golden_treat: { name: '🍖 Golden Treat', desc: 'Shines like gold. Legendary snack!', category: 'collectible' },
  diamond_bone: { name: '💎 Diamond Bone', desc: 'Sparkles with diamonds. Incredible!', category: 'collectible' },
  rainbow_ribbon: { name: '🌈 Rainbow Ribbon', desc: 'Colors shift and change. Magical.', category: 'collectible' },
  companion_treat: { name: '🍖 Companion Treat', desc: 'Special treat for friends. They love it.', category: 'collectible' },
  companion_toy: { name: '🧸 Companion Toy', desc: 'A toy your friends would enjoy.', category: 'collectible' },
}

export const THREATS: Record<string, Threat> = {
  traffic: {
    name: 'Traffic',
    icon: '🚗',
    type: 'timing',
    description: 'Cars are zooming by! Time your crossing!',
    solve: 'Press SPACE when the gap is right',
    mangaText: 'SCREEEECH!',
    mangaType: 'near-miss'
  },
  cat: {
    name: 'Mean Cat',
    icon: '🐱',
    type: 'combat',
    description: 'A hissing cat blocks the path!',
    solve: 'Press SPACE in rhythm to scare it off',
    mangaText: 'SCRATCH!',
    mangaType: 'fight'
  },
  bully: {
    name: 'Bully Dog',
    icon: '🐕‍🦺',
    type: 'combat',
    description: 'A tough-looking dog growls at you!',
    solve: 'Press SPACE in rhythm to intimidate it',
    mangaText: 'GRRR!',
    mangaType: 'fight'
  },
  storm: {
    name: 'Thunderstorm',
    icon: '⛈️',
    type: 'comfort',
    description: 'Thunder roars! Find shelter or comfort yourself.',
    solve: 'Find shelter quickly or use a comfort item',
    mangaText: 'BOOM!',
    mangaType: 'scare'
  },
  vacuum: {
    name: 'Vacuum Monster',
    icon: '🤖',
    type: 'sneak',
    description: 'The dreaded vacuum cleaner! Hide!',
    solve: 'Stay still when it approaches, move when safe',
    mangaText: 'VRRRRR!',
    mangaType: 'scare'
  },
  mailman: {
    name: 'Mail Carrier',
    icon: '📬',
    type: 'timing',
    description: 'The mail carrier is coming! They might have something for you.',
    solve: 'Press SPACE to intercept the mail package',
    mangaText: 'THUMP!',
    mangaType: 'near-miss'
  },
  garden_hose: {
    name: 'Garden Hose',
    icon: '🚿',
    type: 'sneak',
    description: 'A sprinkler is spraying everywhere! Stay dry!',
    solve: 'Move to the dry zone when the sprinkler is away',
    mangaText: 'SPRINKLE!',
    mangaType: 'scare'
  },
  construction: {
    name: 'Construction Crew',
    icon: '🚧',
    type: 'timing',
    description: 'Heavy machinery is working! Watch for the crane!',
    solve: 'Press SPACE when the crane arm is clear',
    mangaText: 'CLANG!',
    mangaType: 'near-miss'
  },
  ice_cream_truck: {
    name: 'Ice Cream Truck',
    icon: '🍦',
    type: 'comfort',
    description: 'The ice cream truck is here! But can you reach it?',
    solve: 'Follow the music and catch the truck before it leaves',
    mangaText: 'DOOOOONG!',
    mangaType: 'scare'
  },
  squirrel: {
    name: 'Squirrel',
    icon: '🐿️',
    type: 'sneak',
    description: 'A squirrel is taunting you from a tree!',
    solve: 'Stay still and wait for the right moment to pounce',
    mangaText: 'SQUEAK!',
    mangaType: 'near-miss'
  },
  neighbor_dog: {
    name: 'Neighbor Dog',
    icon: '🐕',
    type: 'combat',
    description: 'A friendly dog wants to play! But how to respond?',
    solve: 'Press SPACE to bark back or wag tail',
    mangaText: 'WOOF!',
    mangaType: 'fight'
  },
  storm_sewer: {
    name: 'Storm Drain',
    icon: '🕳️',
    type: 'timing',
    description: 'Rain is filling the storm drain! Your toy might be down there!',
    solve: 'Press SPACE to grab the toy before it washes away',
    mangaText: 'WHOOSH!',
    mangaType: 'scare'
  },
  // New threats from new zones
  lake_ripple: {
    name: 'Lake Ripple',
    icon: '🌊',
    type: 'timing',
    description: 'Ripples in the lake! Something is coming!',
    solve: 'Press SPACE to jump over the wave',
    mangaText: 'SPLASH!',
    mangaType: 'scare'
  },
  pet_shop_cat: {
    name: 'Pet Shop Cat',
    icon: '🐱',
    type: 'combat',
    description: 'A pampered cat guards the treats!',
    solve: 'Press SPACE in rhythm to distract it',
    mangaText: 'MEOW!',
    mangaType: 'fight'
  },
  dog_show_judge: {
    name: 'Dog Show Judge',
    icon: '👔',
    type: 'timing',
    description: 'The judge is watching! Pose correctly!',
    solve: 'Press SPACE when the pose indicator aligns',
    mangaText: 'POSE!',
    mangaType: 'near-miss'
  },
  forest_wolf: {
    name: 'Forest Wolf',
    icon: '🐺',
    type: 'combat',
    description: 'A wild wolf blocks the path!',
    solve: 'Press SPACE in rhythm to assert dominance',
    mangaText: 'HOWL!',
    mangaType: 'fight'
  },
  beach_crab: {
    name: 'Beach Crab',
    icon: '🦀',
    type: 'sneak',
    description: 'A crab with giant claws! Hide!',
    solve: 'Stay still when the crab approaches, move when safe',
    mangaText: 'CLICK!',
    mangaType: 'scare'
  },
  mountain_goat: {
    name: 'Mountain Goat',
    icon: '🐐',
    type: 'timing',
    description: 'A goat charges down the mountain!',
    solve: 'Press SPACE to dodge at the right moment',
    mangaText: 'CLACK!',
    mangaType: 'near-miss'
  },
  garden_snake: {
    name: 'Garden Snake',
    icon: '🐍',
    type: 'sneak',
    description: 'A snake slithers through the flowers!',
    solve: 'Move away slowly without sudden movements',
    mangaText: 'HISS!',
    mangaType: 'scare'
  },
  library_silent: {
    name: 'Library Silence',
    icon: '🤫',
    type: 'comfort',
    description: 'The librarian shushes you! Find quiet comfort.',
    solve: 'Find a cozy spot and stay quiet',
    mangaText: 'SHHH!',
    mangaType: 'scare'
  },
  market_chase: {
    name: 'Market Chase',
    icon: '🏃',
    type: 'timing',
    description: 'Vendors are rushing! Dodge the crowd!',
    solve: 'Press SPACE to weave through the crowd',
    mangaText: 'MOVE!',
    mangaType: 'near-miss'
  },
  park_squirrel: {
    name: 'Park Squirrel Army',
    icon: '🐿️',
    type: 'combat',
    description: 'A horde of squirrels attacks!',
    solve: 'Press SPACE in rhythm to scare them off',
    mangaText: 'SQUEAK!',
    mangaType: 'fight'
  },
  // New environmental threats
  fog: {
    name: 'Thick Fog',
    icon: '🌫️',
    type: 'comfort',
    description: 'Visibility is zero! Find your way through.',
    solve: 'Follow the scent trail through the fog',
    mangaText: 'FOG!',
    mangaType: 'scare'
  },
  lightning: {
    name: 'Lightning Strike',
    icon: '⚡',
    type: 'timing',
    description: 'Lightning flashes! Find shelter quickly!',
    solve: 'Press SPACE to run to the nearest shelter',
    mangaText: 'ZAP!',
    mangaType: 'scare'
  },
  flood: {
    name: 'Flash Flood',
    icon: '🌊',
    type: 'sneak',
    description: 'Water is rising! Find high ground!',
    solve: 'Move to elevated areas before the water reaches you',
    mangaText: 'WHOOSH!',
    mangaType: 'scare'
  },
  earthquake: {
    name: 'Earthquake',
    icon: '🌍',
    type: 'timing',
    description: 'The ground is shaking! Stay balanced!',
    solve: 'Press SPACE to stabilize yourself',
    mangaText: 'RUMBLE!',
    mangaType: 'scare'
  },
  // New animal threats
  raccoon: {
    name: 'Raccoon Bandit',
    icon: '🦝',
    type: 'combat',
    description: 'A raccoon steals your items!',
    solve: 'Press SPACE in rhythm to retrieve your things',
    mangaText: 'GRAB!',
    mangaType: 'fight'
  },
  owl: {
    name: 'Night Owl',
    icon: '🦉',
    type: 'comfort',
    description: 'A large owl stares at you in the dark!',
    solve: 'Stay calm and blink slowly to show friendliness',
    mangaText: 'HOOT!',
    mangaType: 'scare'
  },
  deer: {
    name: 'Deer Herd',
    icon: '🦌',
    type: 'sneak',
    description: 'A herd of deer blocks the path!',
    solve: 'Wait patiently for them to move aside',
    mangaText: 'PRANCE!',
    mangaType: 'near-miss'
  },
  // New special threats
  treasure_guardian: {
    name: 'Treasure Guardian',
    icon: '🗡️',
    type: 'combat',
    description: 'A legendary guardian protects the treasure!',
    solve: 'Press SPACE in rhythm to prove your worthiness',
    mangaText: 'CLANG!',
    mangaType: 'fight'
  },
  // New zone-specific threats
  lake_monster: {
    name: 'Lake Monster',
    icon: '🐉',
    type: 'combat',
    description: 'Something large stirs beneath the lake!',
    solve: 'Press SPACE in rhythm to calm the waters',
    mangaText: 'SPLASH!',
    mangaType: 'fight'
  },
  pet_shop_bell: {
    name: 'Pet Shop Bell',
    icon: '🔔',
    type: 'timing',
    description: 'The door bell won\'t stop ringing!',
    solve: 'Press SPACE to silence it before the cat notices',
    mangaText: 'DING!',
    mangaType: 'near-miss'
  },
  dog_show_roar: {
    name: 'Dog Show Roar',
    icon: '🦁',
    type: 'combat',
    description: 'The crowd roars! Stand your ground!',
    solve: 'Press SPACE in rhythm to show confidence',
    mangaText: 'ROAR!',
    mangaType: 'fight'
  },
  forest_thorn: {
    name: 'Forest Thorns',
    icon: '🌿',
    type: 'sneak',
    description: 'Thorny vines block the path!',
    solve: 'Find the safe passage through the thorns',
    mangaText: 'PRICK!',
    mangaType: 'scare'
  },
  beach_wave: {
    name: 'Big Wave',
    icon: '🌊',
    type: 'timing',
    description: 'A huge wave approaches the shore!',
    solve: 'Press SPACE to jump to safety',
    mangaText: 'CRASH!',
    mangaType: 'scare'
  },
  mountain_rockfall: {
    name: 'Rockfall',
    icon: '🪨',
    type: 'timing',
    description: 'Rocks are falling from above!',
    solve: 'Press SPACE to dodge the falling rocks',
    mangaText: 'CLATTER!',
    mangaType: 'scare'
  },
  garden_insect: {
    name: 'Giant Insect',
    icon: '🐛',
    type: 'sneak',
    description: 'A giant bug crawls toward you!',
    solve: 'Stay still and hope it moves on',
    mangaText: 'BUZZ!',
    mangaType: 'scare'
  },
  library_boo: {
    name: 'Library Boo',
    icon: '👻',
    type: 'comfort',
    description: 'A ghostly figure appears among the books!',
    solve: 'Show kindness to the spirit',
    mangaText: 'BOO!',
    mangaType: 'scare'
  },
  market_fire: {
    name: 'Market Fire',
    icon: '🔥',
    type: 'timing',
    description: 'A stall catches fire! Help put it out!',
    solve: 'Press SPACE to grab water buckets',
    mangaText: 'WHOOSH!',
    mangaType: 'scare'
  },
  park_tornado: {
    name: 'Park Tornado',
    icon: '🌪️',
    type: 'sneak',
    description: 'A small tornado forms in the park!',
    solve: 'Find the safest shelter quickly',
    mangaText: 'WHOOSH!',
    mangaType: 'scare'
  }
}

// Export all data as a single object for bootstrapping
export const GAME_DATA = { DOGS, ZONES, ITEMS, THREATS, COMPANIONS };
